### ISSUE TITLE
Chande momentum Oscillator

### ISSUE THREAD

**Issue by Physicworld** [twopirllc/pandas-ta#107]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.1.97b

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
Chande momentum it does not match with trading view values.

**To Reproduce**
Im using this sample of code:

```python
import pandas_ta as TA
chande = TA.cmo(data['close'], length=9)
print(chande.iloc[-1])
```

**Expected behavior**
i check all the configurations and parameters to send cmo function but i didnt get the same result with my code output and Trading view

**Screenshots**
![image](https://user-images.githubusercontent.com/56419395/91929555-42ef6b80-eca4-11ea-9fe9-2a522c47e3e4.png)

this is an example in TV chande value is 17.91 and in the output of chande mom funcition is 51.44
**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @Physicworld,

Thanks for using Pandas TA!

Are you using a different data source for Pandas TA and then visually comparing the numbers displayed from TradingView? If so, then that can cause deviations in calculation because they are not the same data source. You can **Export Chart Data** from TradingView data for comparison by using the _hamburger menu_ in the upper left corner; I use the ISO format.

<img width="342" alt="Screen Shot 2020-09-02 at 7 54 25 AM" src="https://user-images.githubusercontent.com/18198392/91999924-ca170080-ecf1-11ea-911f-c73dabe9ed13.png">

Once you have exported your chart data from TradingView, try the following:
```python
import pandas as pd
import pandas_ta as TA

# Load the TV export data or whatever you saved it as
data = pd.read_csv("path/to/tradingview_data.csv") 
chande = TA.cmo(data['close'], length=9, talib=False)
print(chande.iloc[-1])

# Alternatively
data.ta.cmo(length=9, talib=False, append=True)
print(data.corr()) # Check their correlation
```

Also please reply to this issue with your results so I can see your correlations. You may need to drop some columns before running ```data.corr()``` so it's not filled with extraneous columns.

For example, here my results when exporting from TradingView and turning off TA Lib in **cmo**:

<img width="687" alt="Screen Shot 2020-09-02 at 8 27 18 AM" src="https://user-images.githubusercontent.com/18198392/92005251-1d8c4d00-ecf8-11ea-9411-f4f0a1b60834.png">

> **Expected behavior**
> i check all the configurations and parameters to send cmo function but i didnt get the same result with my code output and Trading view

For details about an indicator, you can use ```help()```:

```python
import pandas_ta as TA
help(TA.cmo)
```

Or if still in doubt, check the [code](https://github.com/twopirllc/pandas-ta/blob/master/pandas_ta/momentum/cmo.py).

For future bugs, remember to use a common data source when comparing indicator results, double check the documentation and/or the code for alternative versions, and provide correlation results.

Add a ⭐  if this library has been useful for you.

Thanks,
KJ

**Comment by twopirllc** [comment]
@Physicworld,

Any progress?

I assume by no response that the response provided was sufficient. Thus I will be closing this issue in a few days.

Thanks,
KJ

**Comment by Physicworld** [comment]
Hello, sorry for the delay, to download trading view data I need to have a pro account and I don't have one.
But I get the data from the binance api, and the prices are always the same.
The value of the chande indicator is different.

**Comment by Physicworld** [comment]
@jit
	def _Chande_mo(self, data, period, threshold):

		chande = TAI.cmo(data['close'], length = period)
		c = chande.iloc[-1]

		print(c)

		if c > threshold:
			return True
		elif c < -threshold:
			return False
		else:
			return 's'

This is my function of chande momentum oscillator if it helps...

**Comment by Physicworld** [comment]
Hey man! i found the error! 

All I had to do was put in false the talib argument!

like this : chande = TAI.cmo(data['close'], length = period, talib = False)

and fix the problem! the values in trading view and chade mom in my code are the same!

Thanks a lot man! i'm building a big trading bot with your library!

**Comment by twopirllc** [comment]
@Physicworld,

> Thanks a lot man! i'm building a big trading bot with your library!
You are welcome! Awesome! Keep me posted!

Glad you found the option. I did post it above in my first reply to you. I was getting confused because I was getting 100% Correlation with TradingView.

Thanks for using Pandas TA!

Thanks,
KJ
