### ISSUE TITLE
Keltner Channel indicator is not the same as tradingview

### ISSUE THREAD

**Issue by SoftDevDanial** [twopirllc/pandas-ta#110]
Hi , is the keltner channel here supposed to be the same as tradingviews builtin keltner channel? The data in trading view doesnt seem to be the same as tradingviews.

**Trading View**
![image](https://user-images.githubusercontent.com/64815604/92155306-c0101180-ee59-11ea-981c-7233c0b49b86.png)

**Pandas_ta*

![image](https://user-images.githubusercontent.com/64815604/92155374-dd44e000-ee59-11ea-888f-918601f4c4ec.png)

**Comment by SoftDevDanial** [comment]
@twopirllc ,

Hey, here is the results after applying the below code.

```
import pandas as pd
import pandas_ta as TA

# Load the TV export data or whatever you saved it as
data = pd.read_csv("msft.csv") 
chande = TA.stoch(data['high'], data['low'] , data['close'])
print(chande.iloc[-1])

# Alternatively
data.ta.stoch(append = True)
print(data.corr()) # Check their correlation
```

**Results**
![image](https://user-images.githubusercontent.com/64815604/92177245-b47d1480-ee72-11ea-84ad-d14857d66764.png)

**Comment by twopirllc** [comment]
@SoftDevDanial 

You are posting Stochastic, but used topic Keltner Channels? If they are separate Issues, please separate them. Also, it's helpful to drop irrelevant columns like time, ohlcv, et al. Makes the correlation matrix smaller 😎 

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
@twopirllc 

OMG :open_mouth: , i was multi tasking doing other indicators that i got it mixed up :flushed:. 
Well , i double checked it this time(Hopefully not gonna do the same mistake again). Below is the results after dropping unnecessary columns. While we are on this correlation topic, do you have any links or reference or even better tell me this correlation function and what is going on in the code. Is data.ta.kc a built in function by pandas because as i understand, data is a pandas dataframe and when running .ta.kc means its running pandas methods.

**Code ( ignore the Util function.. I needed to use my util module to drop irrelevant columns)**
```
import pandas as pd
import pandas_ta as TA
import Util as Util

ut = Util.util()
# Load the TV export data or whatever you saved it as
data = pd.read_csv("Kc.csv") 
chande = TA.kc(data['high'], data['low'] , data['close'])
print(chande)

# Alternatively
data.ta.kc(append = True)
correlate = data.corr() # Check their correlation
dropped = ['time' , 'open', 'high', 'low', 'Upper', 'Basis' , 'Lower' , 'EMA #1' , 'EMA #2' , 'EMA #3', 'EMA #4']
ut.clean(correlate , cols = dropped , index = dropped)
print(correlate)
```
*Results*
![image](https://user-images.githubusercontent.com/64815604/92234782-39087b00-eee5-11ea-877e-0f15cf073555.png)

**Comment by twopirllc** [comment]
@twopirllc 

No worries. 🤣  It happens.

So Correlation is used to determine the relationship between two or more sets of data. If the correlation value is close to zero, then there is little to no relationship. If the value is close to negative one, then there is largely an inverse relationship. Whereas if the value is close to one, then there is largely are direction relationship between the two datasets. More info about Correlation [here](https://en.wikipedia.org/wiki/Correlation_and_dependence).

I use it to test for "Goodness of Fit". When it is close to one, then I know that the two datasets are nearly equivalent. For example, if the value is 0.994, then I know that the calculation is 99.4% fitted. I am content with indicators near 99% correlation mainly with TA Lib and if TA Lib does not have the indicator then TradingView.

Also you dropped the 'Upper', 'Lower', and 'Basis' columns, those are needed for Correlation since those are TradingView's results.  Also Pandas TA has an option like TradingView to use either True Range (the default) or High - Low as it's range calculation.

Give this a run and let me know what you get please:
```python
import pandas as pd
import pandas_ta as TA

data = pd.read_csv("Kc.csv")
# tr=True is the default. Try False also
data.ta.kc(tr=True, append = True)
dropped = ['time' , 'open', 'high', 'low', 'EMA #1' , 'EMA #2' , 'EMA #3', 'EMA #4']
data.drop(columns=dropped, inplace=True)
print(data.corr()
```

Hope this helps!

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
@twopirllc 

ahh i see.. Here you go

![image](https://user-images.githubusercontent.com/64815604/92260630-c90ceb80-ef0a-11ea-9488-077e0272957c.png)


Thanks for the info

**Comment by twopirllc** [comment]
Ahhh thank you!

So, is greater than 99% correlation for each component not good enough? I mean, I know 100% is important, but sometimes it doesn't happen.

KJ

**Comment by SoftDevDanial** [comment]
Well , i did try other modules and the indicators i tried in your library is the closest to tradingview. Well its a bonus if we get 100% but theirs bound to be micro differences which makes it to 99%. 

Thanks for the insight and the help @twopirllc

**Comment by twopirllc** [comment]
@SoftDevDanial,

You are welcome. Thanks for doing the correlation tests and hope you find them useful when comparing data relationships.

Yeah I would love to hit 100% each and every time but it's frankly not realistic sometimes. I do spend a considerable amount of my free time to get it right the first time or close to it. There are so many other features I would like to add but time is not always friendly.

KJ

**Comment by thomascz001** [comment]
Hi,

Tradingview's Keltner Channel also has average true range as entry for range rather than true range and high - low.

Maybe it could be added !

Regards,

Thomas
