### ISSUE TITLE
I'm getting an error while using the PSAR indicator 

### ISSUE THREAD

**Issue by amirsalarsafaei** [twopirllc/pandas-ta#126]
this is the part of code which is getting error:
tmp = ta.psar(df['high'], df['low'], df['close'])
the error is at this line 40:
sar[i] = sar[i - 1] + af * (high_point - sar[i - 1])

**Comment by twopirllc** [comment]
Hello @amirsalarsafaei,

Please follow the **bug** report format. It's there for a reason so that I can ascertain what is truly an issue by providing me with the appropriate context and details without us having the this exchange.

There is not enough details or context here to help you. All my tests pass and no one else has had the same issue. Please be more descriptive in the future.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @amirsalarsafaei!

Please see above.

Thanks,
KJ
