### ISSUE TITLE
Columns get renamed when applying indicators

### ISSUE THREAD

**Issue by xcvb74** [twopirllc/pandas-ta#132]
Hi,

When applying an indicator to an existing Dataframe, using append=True, some of my columns get their first later changed from upper case to lower case. I guess there is some parsing behind this :
```python
print(historic_data.columns)
historic_data.ta.sma(lenght=20, append=True)
print(historic_data.columns)
```
Gets :
```python
Index(['Datetime', 'Week Day', 'Hour', 'Dayofweek_Hour', 'Open', 'Close'], dtype='object')
Index(['datetime', 'Week Day', 'Hour', 'Dayofweek_Hour', 'open', 'close', 'SMA_10'], dtype='object')
```
I then reference those columns to plot and get an error because of the name change.

Version : 0.1.97b

**Comment by twopirllc** [comment]
Hello @xcvb74,

Thanks for using **Pandas TA**!

However it is not a bug. Those columns are preemptively made lowercase so **Pandas TA** can seamlessly processing indicators as a DataFrame extension, like ```df.ta.sma(**kwargs)```. This was outlined in the 2nd Paragraph of the README.

<img width="714" alt="Screen Shot 2020-09-24 at 5 05 56 PM" src="https://user-images.githubusercontent.com/18198392/94212339-c0b02c80-fe88-11ea-871b-9adc4bf4f8ba.png">

I am open to contributions which would handle _any case_. So if you would like to chip in, that would be awesome! Otherwise you can rename those columns in one line after processing the TA.

```python
df.ta.stuff(**kwargs)
# ...
charting_columns = {"open": "Open", "high": "High", "low": "Low", "close": "Close", "adj_close": "Adj Close", "volume": "Volume"}
df.rename(columns=charting_columns, errors="ignore", inplace=True)
```

Drop a :star: if you find the library useful.

Hope this helps,
KJ

**Comment by xcvb74** [comment]
Hey,

Thanks! Obviously I didn't pay attention to this...
Your library is amazing

**Comment by twopirllc** [comment]
@xcvb74,

Thanks! Glad you like it.

KJ
