### ISSUE TITLE
Upgraded pandas_ta to new version, now values changing (without proof).

### ISSUE THREAD

**Issue by ryohno** [twopirllc/pandas-ta#145]
Upgraded pandas_ta without changing any features, and the backtests now show different results. 
I was using version: pandas-ta-0.1.66b0 before, and upgraded to the most recent one. Features of pandas_ta I were using were: _hma, log_return, atr, rsi,bbands, pvt, vwma, sma_. Was there any change in how these calculations were done from previous version to upgraded version?

Particularly, I think there is a discrepancy in applying SMA to a series of volume, or how the bbands were calculated.
For now, I have rolled back to 0.1.66b0.

I expected the same results after update. Why did that happen? Is this library not accurate?

Thanks

**Comment by twopirllc** [comment]
Hello @ryohno,

Thanks for using **Pandas TA**!

This Issue I assume is in regards to your [Neural Net](https://github.com/ryohno/breakout-neural-net/) modules? Why did you disregard the _Bug Report_ questions that I am **once** again having to ask?

> Upgraded pandas_ta without changing any features, and the backtests now show different results.
> ...
> Particularly, I _think_ there is a discrepancy in applying SMA to a series of volume, or how the bbands were calculated.

I'm sorry but anecdotal evidence like _this_ and "I _think_" is **insufficient** to _qualify_ as a **_bug_**. In the future when your projects begin getting Issues, is this level of detail sufficient for you to help resolve their problem?

What backtests? What backtester are you using? Show me outputs/screenshots from Pandas TA v0.1.66b0 and the current version for the **same** asset **and** date range. Is it one asset that seems off or all of them? Include a few of those as well so I know it's not an isolated asset. Where is your proof?

> I expected the same results after update. Why did that happen?

🤷‍♂️  Do you have any correlation tests pinpointing the _inaccuracy_ of the _mentioned_ indicators? Because **none** of the indicators are failing their unit tests on this end and are passing their correlation tests with the _de facto_ TA Lib.

> Is this library not accurate?

Quite the opposite. It is one of the few libraries that **is** accurate. Have you seen other Open Source Python libraries that have passing correlation tests with the de facto TA Lib? Because I have not.

Furthermore, I value my _limited free_ time **seriously** so I can make **Pandas TA** an Open Source TA Library that is _easy to use_, _accurate_ and _feature rich_. Are you implying that I _purposefully choose_ to dedicate my **free** time to make _inaccurate_ indicators?

Lastly major changes are listed on the **README**. Here is the relevant section:

<img width="694" alt="Screen Shot 2020-10-09 at 7 33 48 AM" src="https://user-images.githubusercontent.com/18198392/95596598-6ffd0f80-0a02-11eb-9b7a-91dd054286ce.png">

Regards,
KJ

**Comment by twopirllc** [comment]
Hello @ryohno,

I will be closing out this issue in a few days unless you can convince me _with proof_ that **Pandas TA** is inaccurate despite unit tests to the contrary.

Regards,
KJ
