### ISSUE TITLE
mods to macd to match tradingview

### ISSUE THREAD

**Issue by martin0** [twopirllc/pandas-ta#149]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

0.2.23b0

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
macd wasn't matching results from tradingview
I made a mod to each of 2 files
ema.py line 20
sma_nth = close[0:length].mean() #ensure desired treatment of nan treatment

macd.py line 23
signalma = ema(close=macd.loc[macd.first_valid_index():,], length=signal) # do not process initial nan values

if you agree with these changes, it'd be great to incorporate them into the next release
Thanks

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by martin0** [comment]
Hi KJ,
Thanks for your swift response. I tested with company symbol U for unity, because it is a new ipo (not so much data)
![image](https://user-images.githubusercontent.com/2607781/95889171-fe162480-0d79-11eb-9994-fed168fc2a39.png)

Perhaps i should use some kwargs to achieve the matching result, but i'm not too familiar with kwargs at this time.

**Comment by martin0** [comment]
I'm delayed on this, as I'm also trying to get rsi to match TradingView. There's an issue with Wilder's Moving Average...

**Comment by martin0** [comment]
I can't export the data as I'm not subscribed to TradingView,

**Comment by twopirllc** [comment]
So the first few bars of an indicator are your concern since you posted an IPO chart?

> I'm delayed on this, as I'm also trying to get rsi to match TradingView. There's an issue with Wilder's Moving Average...

These are **all** baseless claims and the burden of proof lies in your court. Until then, none of these are issues. I have already put in copious amounts of limited **free** time to ensure the accuracy of each indicator in this package.

Regards,
KJ

**Comment by martin0** [comment]
I'm sorry you feel bad. I have also put in "free" time to make sure the values match TradingView, and shared the corrections I made. I have also adjusted rma and rsi, but unless you're interested, I don't see the point in sharing the details.
I think what's interesting is what the definition of "correct" is. Perhaps TradingView is wrong...?

**Comment by twopirllc** [comment]
I apologize if I appear defensive. But I have gotten and will continue to get Issues along the lines of "Indicator Yabb-Do is incorrect with TradingView/Webull ..." and their level of proof is similar to the following or nothing at all.

```python
datetime | Yabba_10 | Do_15
8/22/2020 10:00 | 23.2039 | 20.5802
8/22/2020 11:00 | 54.0628 | 32.7028
8/22/2020 12:00 | 78.2172 | 51.9909
8/22/2020 13:00 | 95.7515 | 76.1622

# But very off from charts TradingView/Webull:
8/22/2020 10:00 | 14.46 | 21.09
8/22/2020 11:00 | 14.32 | 14.64
8/22/2020 12:00 | 45.65 | 23.81
8/22/2020 13:00 | 78.22 | 46.07
```

🤷‍♂️ 

> I would prefer if we could collaborate. Please let me know if you would like this.

Likewise. Nowhere in this Issue have I stated that I am against collaboration. In fact, I prefer it so that I can continue adding _new_ features and indicators.

> I have also put in "free" time to make sure the values match TradingView (TV), and shared the corrections I made. I have also adjusted rma and rsi, but unless you're interested, I don't see the point in sharing the details.

Great! Fork the repository, edit, and make a Pull Request so you get collaboration credit and everyone benefits.

> I think what's interesting is what the definition of "correct" is. Perhaps TradingView is wrong...?

It's great when there is 1-1 correspondence of indicator calculations irregardless of the underlying language (C, Python, Pinescript, ...) with the same data set. Sadly that is not always the case. Though it is imperative to get the _core_ indicators such as **sma**, **ema**, et al near 1-1. However for the majority of _non-core_ indicators, there can be endless minute variations across trading platforms and even harder to correlate if there is no accompanying source or it is proprietary.

TradingView (TV) is widely used, as you know, so I doubt their code is "incorrect". I have and do correlation tests with TV, as I previously linked, when necessary or when replicating someone's request for an indicator that is publicly available.

Regards,
KJ
