### ISSUE TITLE
stochastic is off (without proof)

### ISSUE THREAD

**Issue by qnguye** [twopirllc/pandas-ta#150]
AAPL ticker for example. I ran 5 days 5 min chart. This is the first few stoch data for AAPL at open on 10/14/20

datetime | STOCHk_14_3_3 | STOCHd_14_3_3
10/14/2020 9:30 | 23.21256039 | 20.56580296
10/14/2020 9:35 | 54.5410628 | 32.70238618
10/14/2020 9:40 | 78.21922372 | 51.99094897
10/14/2020 9:45 | 95.77775215 | 76.17934622

but results very off compare to my charts (webull/trading view)
10/14/2020 9:30 | 14.46 | 21.09
10/14/2020 9:35 | 14.32 | 14.64
10/14/2020 9:40 | 45.65 | 23.81
10/14/2020 9:45 | 78.22 | 46.07

**Comment by twopirllc** [comment]
Hello @qnguye,

Thanks for using **Pandas TA**!

You have deleted _all_ relevant questions for a bug report including what version you are using and provided no screenshots other than a copy paste of "some" values. You do not show any parameters used from Webull/TradingView since they are omitted in your output. You sure you have the same parameters?

There is no substance other than anecdotal evidence. You have not provided any correlation tests to show any differences over a large set of data; unfortunately, four data points are insufficient.

If you really want to convince me that **stoch** is _incorrect_, then please follow Issue #107 on how to _Export Chart Data_ from TradingView **and** perform a correlation test. Also, please read about **stoch** and **stochrsi** in Issue #112.

Until then, this is **not** a bug nor a valid issue.

Regards,
KJ

**Comment by qnguye** [comment]
I'm on version 0.2.23b0
I'm using default stochastic value 14,3,3 on all. I attach the CSV with price datas and screenshot of TradingView & Webull
[AAPL_5d5m_stochastic.zip](https://github.com/twopirllc/pandas-ta/files/5381342/AAPL_5d5m_stochastic.zip)

**Comment by twopirllc** [comment]
@qnguye 

Great! However, these chart screenshots of are **not** replacements for numerical correlation test results. Furthermore, visualization is a _minimum_ bar to accomplish and you have not shown me results any results of Pandas TA's **stoch** chart in comparison to either Webull nor TradingView to compare against.

More importantly, you have not run _any_ correlation tests like described in Issue #107 that would provide evidence that **stoch** is inaccurate.

I want to be very clear that I am **not** opposed to having different **stoch** variations based on source (TA Lib, TradingView, Webull, whatever...). I have already tested **stoch** with TradingView and have very high correlation test results. If you want a condition based on Webull, which may calculate **stoch** _differently_ from the de facto TA Lib or well known TradingView, I need a copy of the source of the indicator so that I can get them correlated.

Also, is the csv from TradingView or Webull? Because that was **not** clear in the zip file.

Did you want me to process the _csv_ and do it? Because if so, that is **not** a priority since I have already correlated it with TradingView as previously mentioned in the linked Issues in my prior comment.

I am **not** trying to be difficult. This is **not** a top priority nor a **bug** since I have dedicated _considerable_ personal limited **free** time on this Open Source project to make sure that the indicators are accurate to begin with.

You are almost there.

Thanks,
KJ

**Comment by qnguye** [comment]
In the CSV is a processed file. The last 2 columns (STOCHk_14_3_3, STOCHd_14_3_3) are results of Pandas TA's stoch. I can't export tradingview because i don't have paid version. The CSV open,high,low,close,volume data i got from td ameritrade, which is almost 99% identical with tradingview. I guess those small fractions can yield big different results. MACD, EMA, bbands are vey close, just this stoch is off a lot to me. I know you guys spent crazy amount of time for this project. Big thanks.

**Comment by twopirllc** [comment]
> I guess those small fractions can yield big different results.

Yes.

> The last 2 columns (STOCHk_14_3_3, STOCHd_14_3_3) are results of Pandas TA's stoch.

Yes. So where are the TD Ameritrade **stoch** results?
