### ISSUE TITLE
How about supertrend indicator parameters?

### ISSUE THREAD

**Issue by andy60** [twopirllc/pandas-ta#170]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

0.2.23b0

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
```python
from pandas_datareader import data as pdr
import pandas_ta as ta
import yfinance as yf
yf.pdr_override()
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2018-04-30")
data.ta.cores = 2
data['ema50']=ta.ema(data['close'],50)
data['ema150']=ta.ema(data['close'],150)
data['ema200']=ta.ema(data['close'],200)
data['RSI']=ta.rsi(data['close'], 14)
```
i want to calculate supertrend indicator but i dont find the correct parameters for the function.

**Describe alternatives you've considered**
nd

**Additional context**
nd

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @andy60,

Thanks for trying **Pandas TA**!

## Upgrade

First, please upgrade to the latest version ```0.2.28b```.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

## Help

For help with an indicator or method, use Python's builtin ```help()``` command (which prints the __doc__ of the function or method).
```python
help(ta.supertrend)
```

## Usage

Pandas TA has different programming conventions for using the library. **Conventionally** as you have done, using it as a **Pandas TA DataFrame Extension** ```df.ta```, or using a **Pandas TA Strategy** ```df.ta.strategy(youStrategy)```.

Note: To make use of cores, you have to use a Pandas TA Strategy.

### **Pre-Analysis:** Imports and Data Acquisition
```python
import pandas as pd
import pandas_ta as ta
from pandas_datareader import data as pdr
yf.pdr_override()

data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2018-04-30")
```

### **Conventionally** (like TA Lib)
```python
data['ema50'] = ta.ema(data['Close'],50)
data['ema150'] = ta.ema(data['Close'],150)
data['ema200'] = ta.ema(data['Close'],200)
data['RSI'] = ta.rsi(data['Close'], 14)
data['SUPERTR'] = ta.supertrend(data['Close'])
```

### **Pandas TA DataFrame Extension**
```python
data.ta.ema(length=50, append=True)
data.ta.ema(length=150, append=True)
data.ta.ema(length=200, append=True)
data.ta.rsi(append=True)
data.ta.supertrend(append=True)
print(data.columns) # Columns automatically added to data DataFrame 
```

### **Pandas TA Strategy**
```python
# (1) Create the Strategy
myTA = ta.Strategy(
    name="My Strat",
    ta=[
        {"kind": "ema", "length": 50},
        {"kind": "ema", "length": 150},
        {"kind": "ema", "length": 200},
        {"kind": "rsi"},
        {"kind": "supertrend"},
    ]
)

# (2) Run the Strategy
data.ta.cores = 2 # If needed, set the cores.
data.ta.strategy(myTA, verbose=True)

print(data.columns) # Columns automatically added to data DataFrame 
```

Either of these programming conventions will yield the same result: each indicator ran and appended to the ```data``` DataFrame. Use whichever convention is easiest, but I find the last convention the most convenient since you can easily define and run them all with little manipulation.

Much of this is covered in the [README](https://github.com/twopirllc/pandas-ta) as well as some [Examples](https://github.com/twopirllc/pandas-ta/tree/master/examples).

Let me know if this works! Hope it helps!

Regards,
KJ

**Comment by twopirllc** [comment]
Hello @andy60,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Thanks,
KJ
