### ISSUE TITLE
Newb Problem with get_column Error/Warning

### ISSUE THREAD

**Issue by John64** [twopirllc/pandas-ta#171]
New to pandas-ta & not a programmer by profession

Any help or suggestions would be appreciated.  I have the following 1 line of code below that is utilizing vwma.  I've checked the output mathematics in Excel & it appears to be working fine, but I'm getting a long series of the Error below.  Searching others issues here, I gather that it's the 'def _get_column' that's being triggered.  I'm not sure why it's looking for a column when I've specified them below and confirmed that it is indeed using them to calculate??  I also checked the '_average' (price) & '_volume' columns referenced below & confirmed there are no 'na' values in the series.

Any help would be appreciated.  It's cluttering up my Jupyter notebook.  Couldn't find a way to suppress the warning/error message either??

```python
for num in vwap_nums:
        #generates issues below, but doesn't seem to effect anything
        feat_df[symb + '_VWAP_' + str(num)] = feat_df.ta.vwma(close=symb + '_average', volume=symb + '_volume', offset=0, length=num)
```

```sh
Error:  
`[X] Ooops!!!: It's True, the series 'volume' was not found in index, date, day_dt, dayofweek, max_time`
```

...(continues on listing all columns in the dataframe)

**Comment by twopirllc** [comment]
Hello @John64,

I have been having some ISP issues lately. I will respond in depth as soon as it is more stable hopefully by the end of the day. Apologies.

KJ

**Comment by twopirllc** [comment]
Hello @John64,

> New to pandas-ta & not a programmer by profession

No worries. Thanks for waiting. I appreciate it.

Based on the code provided, it appears that you are building a single _DataFrame_ of multiple _Symbols_ containing different __vwmas__ of various lengths of the _Symbol's Average_. The only reason you are getting the ```_get_column()``` error is because you are calling **vwma** using the Pandas TA DataFrame Extension. For the code you provided, I would just use Conventional calling which does not rely on ```_get_column()```. A slight change like the following should work, otherwise let me know.

```python
# if feat_df.columns = ["AA_average", "AA_volume", "Z_average", "Z_volume"]
for num in vwap_nums:
    feat_df[f"{symb}_VWMA_{num}"] = ta.vwma(close=feat_df[f"{symb}_average"], volume=feat_df[f"{symb}_volume"], length=num)
```

While there is nothing wrong with your approach for what you are trying to accomplishing prior to post-analysis. I do want to point out that a Pandas TA DataFrame represents one _Symbol_ for the purposes of applying TA to the DataFrame. But of course you are not limited to do so and hence why the package supports Conventional calling; it just requires more code.

Keep me posted. Hope this helps!

Thanks,
KJ

**Comment by John64** [comment]
Perfect! Thank You
On a side note, I was getting small, couple cent differences on $100 stocks between Excel and pandas-ta vwma when there were errors/warnings.  Figured it was rounding, but now all values are difference of exactly 0. Guess that's why one shouldn't ignore errors :)

**Comment by twopirllc** [comment]
Excellent! Thanks for letting me know.

That's weird that getting cent differences. No numerical transformations are performed after an indicator is returned. But thanks for the potential heads up.

Thanks,
KJ
