### ISSUE TITLE
ATR difference with TV (without proof)

### ISSUE THREAD

**Issue by 2W-12** [twopirllc/pandas-ta#187]
ATR in TradingView giving completely different results.

**Comment by twopirllc** [comment]
Hello @2W-12,

I would like to help you, however you have not filled out the **Bug Report** sufficiently in order to classify this as a **bug**. For instance, you have **not shared** any code or screenshots nor provide insight to your programming environment such as the Pandas TA version and which OS you use. **All** of which was asked on the Bug Report form in the first place (so I wouldn't have to ask these questions again 🤷🏼‍♂️ ). Why are you exempt from this simple procedure?

Additionally, this is the _second_ **baseless claim** you have made. Unfortunately, anecdotal claims are insufficient evidence in anything STEM related and the law. If you would like for me to investigate this issue, you need some **hard evidence**. Preferably a _simple correlation analysis_ between TV and Pandas TA (as mentioned on the [README Issues](https://github.com/twopirllc/pandas-ta#issues-and-contributions)).

<img width="398" alt="Screen Shot 2021-01-07 at 8 37 41 AM" src="https://user-images.githubusercontent.com/18198392/103918997-5d0edf80-50c4-11eb-9976-49dfec9272e4.png">

I will look into your claim **after** you have taken some time to _read_ [Issue #107 - CMO and TradingView Export](https://github.com/twopirllc/pandas-ta/issues/107), _export_ **and** do a _correlation test_ to prove ATR is in fact inaccurate. Even a screenshot of the two, TV and Python, would add more support.

Lastly, have you read the _help()_ on ATR or any indicator as mentioned in the README? Have you played around with the parameters?

It is as simple as:
```python
import pandas_ta as ta
help(ta.atr)
```

Finally, I want to be clear that I am open to changes and fixes as needed but I can not do it on limited knowledge and no proof.

Please reopen this Issue when you have given me to work with.

Regards,
KJ
