### ISSUE TITLE
Different (wrong?) Bollinger Bands values than TradingView. 

### ISSUE THREAD

**Issue by JorisArends** [twopirllc/pandas-ta#218]
Hi, I was wondering why my **Bollinger Bands values are different** from the one on tradingview. I use the OHLC data from the same exchange (Binance) and the BB values differ sometimes. For example, my program calculated that the candle of **IOTXUSDT** at **22:15 UTC+1** **(5M timeframe 07-02-2021)** had opened / closed underneath the lowest Bollinger Band. If I take a look at this coin on TradingView, the OHLC data is the same as i've imported, but the BBands values are different, even when the settings are the same on both sides. 

I've attached some screenshots with my data that was calculated by pandas-ta and the TradingView screenshot where you can see that the price has not even touched the lowest Bollinger Band.

**Values of the BBand Low:**
Pandas-TA = 0.013836
TradingView  = 0.013635 (correct one?)

[Dataframe row with my data from binance and pandas-ta](https://prnt.sc/ymfcpi)
[See tradingview screenshot for the 22:15 UTC+1 mark](https://prnt.sc/ymfkbu)
I'm on version 0.2.23b0 

I couldn't find the problem why this data is different to the one on tradingview or the broker. I hope someone can help me with this problem 👍

**Comment by twopirllc** [comment]
Hello @JorisArends,

> I'm on version 0.2.23b0

The current version is ```0.2.42b``` First, upgraded like the Bug Report Form Suggests:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

> Hi, I was wondering why my Bollinger Bands values are different from the one on tradingview.

In short, there is no easy way to test **All** the indicators on TradingView with Pandas TA without _manually_ downloading . It is much easier to test **All** the indicators with TA Lib; which is the _de facto_ TA library used by many other platforms and other user _repos_.  **Please** read Issue #202 about Bollinger Bands and how I test indicators in Pandas TA in general. If you know a way to test **All** the Pandas TA indicators with TradingView indicators **without** manually creating a separate TradingView chart and exporting the data and manually downloading it, I am all ears and would love an automated solution.

If you would like to see this issue resolved sooner, please add a specific TradingView version by _forking_, _editing_ and submitting a _PR_. Also when submitting your _PR_, please provide TradingView data you used, TradingView's **bbands** data for comparison with Pandas TA as well as provide results of your improved **bbands** with a correlation test showing the improvement you have made. (See Issue #107 on Correlation Testing with TradingView).

I am closing this Issue since it is related with Issue #202; Bollinger Band enhancement. All future discussion regarding this Issue will take place in Issue #202 so all the problems/solutions can be hashed out in one place.

Kind Regards,
KJ
