### ISSUE TITLE
Issues with ADX

### ISSUE THREAD

**Issue by RNPhelan** [twopirllc/pandas-ta#232]
Hello. First, thank you for your excellent work on pandas ta! 

I am getting strange values for ta.adx. Namely, all ADX values are NaN. 

Do you have any thoughts? Is this a bug? Thank you.

Here are the details.

# Version
import pandas as pa
import pandas_ta as ta
print(ta.version)
0.2.42b0

# DATAFRAME (1-month data for NVDA (Nvidia) from 2/17/201)

<img width="419" alt="data" src="https://user-images.githubusercontent.com/60681316/108215570-1666c900-70f7-11eb-9842-03a048293c89.PNG">

# CODE - GET ADX VALUES USING PANDAS TA

adx = ta.adx(high=df['High'], low=df['Low'], close=df['Close'], length=14)
print(adx)

# ADX OUTPUT 

Note the ADX values are NaN. Any ideas? 

<img width="201" alt="Capture" src="https://user-images.githubusercontent.com/60681316/108299809-c1fa3280-7164-11eb-8361-eaa79cf7a8d1.PNG">

**Comment by RNPhelan** [comment]
Okay, I see the error now. Basically, you need to supply ta.adx with enough data. In the above, I was only providing 1 month's data. This is not enough. It is recommended that you supply at least 150 days of data for consistency. See:  https://wallmine.com/term-definitions/adx_14

After I supplied 150 days of data, then pandas-ta ta.adx worked perfectly, matching values at tradingview and alpha vantage with high correlation. Excellent work pandas-ta team!

**Comment by twopirllc** [comment]
Hello @RNPhelan,

> Hello. First, thank you for your excellent work on pandas ta!

Thanks for using Pandas TA! I apologize for the late reply.

> Okay, I see the error now. Basically, you need to supply ta.adx with enough data. In the above, I was only providing 1 month's data. This is not enough. It is recommended that you supply at least 150 days of data for consistency. See: https://wallmine.com/term-definitions/adx_14

Yes. The reason is based on how **adx** is calculated. Internally, it has a two chain **rma** calculation so it's resultant length will be ```2 * length``` or _28_ with the default length.

Here is test output for **adx** (```adx.head(30)```):
![Screen Shot 2021-02-18 at 8 32 49 AM](https://user-images.githubusercontent.com/18198392/108389036-1a145180-71c4-11eb-84b8-fd70f7c3d0ea.png)

<br/>

Alternatively, you could have ran **adx** from the DataFrame.
```python
# adx = ta.adx(high=df['High'], low=df['Low'], close=df['Close'], length=14)
print(adx)

# As DataFrame Extension
df = # your data
df.ta.adx(append=True)
print(df)
```

<br/>

> After I supplied 150 days of data, then pandas-ta ta.adx worked perfectly, matching values at tradingview and alpha vantage with high correlation. Excellent work pandas-ta team!

Awesome! Thank you! 😎 

Kind Regards,
KJ
