### ISSUE TITLE
Tradingview RSI

### ISSUE THREAD

**Issue by sword134** [twopirllc/pandas-ta#233]
The current RSI is not the same as the one on Tradingview. I have so far been unable to find an RSI indicator for Python which mimics that of Tradingview. Adding it here in Pandas_ta (my favourite ta library) would be perfect!

**Comment by twopirllc** [comment]
Hello @sword134,

Are you comparing two different data sources, TradingView and your own? Have you exported TradingView's _ohlcv_ data and **rsi** values and done a _correlation_ test with Pandas TA? I also recommend reading Issue #69.

Since you have not indicated your Pandas TA version, you should upgrade to the Latest Version (*0.2.42b*):
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

> Adding it here in Pandas_ta (my favourite ta library) would be perfect!

Thanks! But it seems ```qtpylib``` is your favorite. Just messing with you.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @sword134,

How is this coming along? Have you exported data from TV and run a correlation test yet?

I will be closing this Issue in the new few days if there is no continued activity. Feel free to reopen when you are ready to continue this Issue.

Kind Regards,
KJ
