### ISSUE TITLE
Trend: Increasing, Descreasing Help

### ISSUE THREAD

**Issue by ben1628** [twopirllc/pandas-ta#278]
Can someone explain to me the use of Increasing/Decreasing.

I want to test the Close price of a stock and find out whether it's increasing.  If it is greater than a certain percentage from the previous close, it will return true.

How do we find out how long whether the previous/previous is also increasing?

An example will be just great.

**Comment by twopirllc** [comment]
Hello @ben1628,

## Increasing (rising) / Decreasing (falling)
So **increasing/decreasing** returns 1 if the current bar is greater/less than any previous bar for ```length``` bars back, 0 otherwise. Use ```help(ta.increasing)``` for more options. They are modeled after```rising/falling``` in [TradingView's builtin functions](https://www.tradingview.com/pine-script-reference/v4/). [falling](https://www.tradingview.com/pine-script-reference/v4/#fun_falling) and [rising](https://www.tradingview.com/pine-script-reference/v4/#fun_rising)

Essentially:
```python
decreasing = current_value.diff(length) < 0
increasing = current_value.diff(length) > 0
```

## Examples and Alternatives

```python
import pandas as pd
import pandas_ta as ta

t = 2 * ta.RATE["TRADING_DAYS_PER_YEAR"]

df = # ohlcv of SPY
spy = df.copy()

ema5 = spy.ta.ema(length=5, append=True)
ema20 = spy.ta.ema(length=20, append=True)
ema50 = spy.ta.ema(length=50, append=True)
ema200 = spy.ta.ema(length=200, append=True)
spy[["close", "EMA_5", "EMA_20"]].tail(t).plot(figsize=(16, 8), color=["black", "green", "orange"], grid=True)
```

<img width="747" alt="Screen Shot 2021-04-25 at 5 01 07 PM" src="https://user-images.githubusercontent.com/18198392/116014416-0f25d500-a5ea-11eb-810f-52edcaaccaff.png">

```python
# Plot of when close.diff(2) > 0 or increasing(close, 2) or rising(close, 2)
spy.ta.increasing(length=2, append=True) # Column: "INC_2"
spy["INC_2"].tail(t).plot(figsize=(16, 1.2), kind="area", color=["black"], alpha=0.35, title=f"Close_INC_2", grid=True)
```

<img width="746" alt="Screen Shot 2021-04-25 at 5 01 15 PM" src="https://user-images.githubusercontent.com/18198392/116014433-1ea51e00-a5ea-11eb-9b67-9beb67bf0d80.png">

```python
# Plot of when ema5.diff(2) > 0 or increasing(ema5, 2) or rising(ema5, 2)
# Smoothed Prices yield more consistent trends
spy["INCEMA5_2"] = ta.increasing(ema5, length=2)
spy["INCEMA5_2"].tail(t).plot(figsize=(16, 1.2), kind="area", color=["green"], alpha=0.35, title="INCEMA5_2", grid=True)
```

<img width="744" alt="Screen Shot 2021-04-25 at 5 01 25 PM" src="https://user-images.githubusercontent.com/18198392/116014445-2ebcfd80-a5ea-11eb-87c2-d7c84e1528ca.png">

```python
# Plot of when ema20.diff(2) > 0 or increasing(ema20, 2) or rising(ema20, 2)
# Even better when looking for long signals with a bit longer MA
spy["INCEMA20_2"] = ta.increasing(ta.ema(spy.close, length=20), length=2)
spy["INCEMA20_2"].tail(t).plot(figsize=(16, 1.2), kind="area", color=["orange"], alpha=0.35, title="INCEMA20_2", grid=True)
```

<img width="744" alt="Screen Shot 2021-04-25 at 5 01 36 PM" src="https://user-images.githubusercontent.com/18198392/116014460-41373700-a5ea-11eb-99ae-ecfdc94868fb.png">

```python
spy[["close", "EMA_50", "EMA_200"]].tail(t).plot(figsize=(16, 8), color=["black", "red", "maroon"], grid=True)
```

<img width="749" alt="Screen Shot 2021-04-25 at 5 01 43 PM" src="https://user-images.githubusercontent.com/18198392/116014483-5c09ab80-a5ea-11eb-960b-773448bb994f.png">

```python
# Even better, we can use long_run() to take two series and find both are about to cross
# or if both series are increasing. More powerful with longer lengths. Can even lead into
# MA crossovers before they happen.
spy["EMA50_200_LR_2"] = ta.long_run(fast=ema50, slow=ema200)
spy["EMA50_200_LR_2"].tail(t).plot(figsize=(16, 1.2), kind="area", color=["red"], alpha=0.35, title="EMA50_200_LR_2", grid=True)
```

<img width="748" alt="Screen Shot 2021-04-25 at 5 01 54 PM" src="https://user-images.githubusercontent.com/18198392/116014489-62982300-a5ea-11eb-854e-eb46898c206e.png">

<br/>

## Percent Return Threshold

>  If it is greater than a certain percentage from the previous close, it will return true.

Here is what came to my mind. Certainly it can and should be improved.

```python
spy = df.copy()
spy["close"].tail(t).plot(figsize=(16, 8), color=["black"], title="SPY", grid=True)
```

<img width="757" alt="Screen Shot 2021-04-25 at 5 41 51 PM" src="https://user-images.githubusercontent.com/18198392/116015379-e0116280-a5ed-11eb-8dae-ee1f66fe40ea.png">

```python
pct = 0.05 # 5% threshold
pctret = spy.ta.percent_return(append=True)
pctret.tail(t).plot(figsize=(16, 2), color=["black"], title="PCTRET_1", grid=True)
pct_signals = pd.DataFrame({
    f"PCTgt_{pct}": np.where(pctret >= pct, 1, 0),
    f"PCTlt_{pct}": np.where(pctret <= -pct, 1, 0)
}, index=pctret.index)
pct_signals.tail(t).plot(figsize=(16, 1.2), color=["green", "red"], title=f"{100 * pct:.2f}% PCT Threshold", grid=True).axhline(0, color="black")
```

<img width="747" alt="Screen Shot 2021-04-25 at 5 43 48 PM" src="https://user-images.githubusercontent.com/18198392/116015398-ed2e5180-a5ed-11eb-8d99-cc6cf2ca5778.png">

<br/>

> How do we find out how long whether the previous/previous is also increasing?

Sorry. Unsure what you mean. 🤷🏼‍♂️

Hope this helps!

Kind Regards,
KJ

**Comment by ben1628** [comment]
Thanks.
