### ISSUE TITLE
[Enhancement] Naming of the Accumulation/Distribution Indicator

### ISSUE THREAD

**Issue by WilliamDesmas** [twopirllc/pandas-ta#28]
Hello,

Thank you for your great work.

Regarding the Accumulation/Distribution indicator, it's possible to have two versions of it: using close and open OR using close, high and low. However, if I'm not mistaken, as they would have the same name, it is impossible to have the two versions inside the same dataframe (without renaming).

Could you please dynamically name the series regarding the version chosen?

Thanks

**Comment by twopirllc** [comment]
Hello William,

Thanks!

AD is an interesting indicator because of it's dual nature.  I have implemented both versions, but you are correct that it does not specifically name which version is used; both versions currently return "AD".  More info with: ```help(ta.ad)```  For the version utilizing 'open', how about I set it's name as: "ADo" not to be confused with "AD" and "ADOSC"?  That would be the quick fix.  What do you think?

Thanks

**Comment by twopirllc** [comment]
William,

It is now set to return the name "ADo" if you include the open argument, otherwise it returns the name "AD".

Hope this helps!

**Comment by WilliamDesmas** [comment]
Hello,
Thanks a lot for your replies.
Yes, this is solving the "issue".
Have a nice week-end
