### ISSUE TITLE
why change name of OHLCV?

### ISSUE THREAD

**Issue by wenny0501** [twopirllc/pandas-ta#310]
Hi, when we use df.ta.ticker() to download historical data, the original name of  OHLCV are "Open, High, Low, Close, Volume", but when we apply other ta function, the name of OHLCV become "open, high, low, close, volume". 
so, my question is : can we not change the name of OHLCV?
thanks

**Comment by twopirllc** [comment]
Hello @wenny0501,

You are correct, when using ```df.ta.ticker()``` the OHLCV column names are returned in Title case. I am preserving the original column names that **yfinance** uses since that is the default.

You are also correct when applying indicators using DataFrame Extension Convention, it automatically lowercases the column names as described under the DataFrame Extension section in [Programming Conventions](https://github.com/twopirllc/pandas-ta#programming-conventions). You can see Issue #177 on resetting the names to whichever case you prefer after processing your indicators.

Hope this makes sense.

Kind Regards,
KJ
