### ISSUE TITLE
PPO indicator uses sma instead of ema for fast and slow series

### ISSUE THREAD

**Issue by GhostusSK** [twopirllc/pandas-ta#321]
From my understanding the PPO indicator should be similar to the MACD indicator. The main difference is that the PPO shows percentage results. That means, that for same fast, slow and signal parameters both indicators should have cross-sections between signal and macd line at the same time. In your current implementation the PPO cross-sections differ from the MACD indicator cross-sections. I've checked both indicators on the TradingView and TradingView shows the cross-sections for both indicators at the same time.

When I investigated your code, I noticed that for MACD you are using ema for calculation fast and slow series, but for PPO indicator you are using sma. I think that the PPO should also use the ema.

**Comment by twopirllc** [comment]
Hello @GhostusSK,

Unfortunately, this is **not** a bug and sadly there are **no** TA Standards that exist that **mandates** how indicators must work. There are no RFP or RFCs. It is the Wild West in this regard and clearly causes confusion.

> When I investigated your code, I noticed that for MACD you are using ema for calculation fast and slow series, but for PPO indicator you are using sma. 

This is correct because [TA Lib](https://www.ta-lib.org/hdr_dw.html), which many users also use and rely on, originally chose _MACD_ to use **ema** and _PPO_ use **sma**. 

For easier testing, I use TA Lib to ensure that the indicators are accurate and tightly correlated. For instance here is [_PPO_](https://github.com/twopirllc/pandas-ta/blob/0f38504cce6c9495c044896fcd3f6fee3a8b46be/tests/test_indicator_momentum.py#L266). When using **sma** I get 99.99+% correlation whereas with **ema** I get 90.79+% correlation with TA Lib.

In contrast to TradingView where it is not so easy to test against; it's a manual process. See [How to Correlation Test versus TradingView (Issue #107)](https://github.com/twopirllc/pandas-ta/issues/107) They unfortunately do not allow REST access to data, but they do for [Brokers](https://www.tradingview.com/support/solutions/43000474413-i-need-access-to-your-api-in-order-to-get-data-or-indicator-values/); maybe one day 🤷🏼‍♂️ . (I've been waiting for years

Considering PPO, it seems they have also made **sma** & **ema** optionable. I do not recall if it was one or the other prior to Version 4 (Instance 24).

<img width="751" alt="Screen Shot 2021-06-28 at 2 56 55 PM" src="https://user-images.githubusercontent.com/18198392/123709088-50707600-d821-11eb-9e3d-ac847a128351.png">

<br/>

> I think that the PPO should also use the ema.

This is fine and can easily be done. [Here](https://github.com/twopirllc/pandas-ta/search?q=mamode) are was of implementing it with PPO or any other indicator that uses some "ma" using **mamode**. If you want some contribution credit, feel free to fork, edit and submit a PR. 😎  Otherwise I will work it in amongst other Issues.

Hope this makes sense and clarifies things. Thanks for using Pandas TA!

Kind Regards,
KJ

**Comment by GhostusSK** [comment]
Thank you for fast response and such detailed clarification. I'm just a beginner with python, so I will rather wait until you implement the solution amongst other issues.

Thank you for great work at the Pandas TA.

**Comment by twopirllc** [comment]
@GhostusSK,

No worries.

Thank you
KJ

**Comment by twopirllc** [comment]
Hello @GhostusSK,

It's been added. You can use it by passing the parameters: ```ta.ppo(..., mamode="ema",...)```. Let me know if it is working for you when you get a chance.

Thanks,
KJ

**Comment by GhostusSK** [comment]
Hello @twopirllc ,

I've just tried the mamode parameter and it is working as I expected. 

Thank you.

**Comment by twopirllc** [comment]
@GhostusSK,

Great! Thanks for the prompt response.

KJ
