### ISSUE TITLE
ATR moving average selection.

### ISSUE THREAD

**Issue by Khunaus** [twopirllc/pandas-ta#328]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.2b0

**Describe the bug**
The ATR indicator does not seem to adopt different moving average inputs

**To Reproduce**
```python
df.ta.atr(length=14, mamode="sma", append=True)
df.ta.atr(length=14, mamode="ema", append=True)
df.ta.atr(length=14, mamode="wma", append=True)
df.ta.atr(length=14, mamode="rma", append=True)
```

**Expected behaviour**
all of these modes produce the same value, however these should produce slightly different values due to the different moving average calculations.  any advice on how to resolve?

Thanks for using Pandas TA!

Thank you

**Comment by twopirllc** [comment]
Hello @Khunaus,

Since you are using _v0.3.2b_ and likely have TA Lib installed, then **atr** will use TA Lib's [**atr**](https://github.com/twopirllc/pandas-ta/blob/1deb7559f626d2a5cf664b6c0af7a8016a53bfca/pandas_ta/volatility/atr.py#L22) which does not support other _ma_'s.

For now, this is the default behavior _with_ TA Lib installed. However, It appears I need to make it optionable a well. Until I can do that, you have a few options but you will have to edit your local copy.

Disable
---
The simplest option if you plan not to utilize TA Lib's **atr** edit:
(```/path_to_local_pandas_ta/pandas_ta/volatility/atr.py```)

Just set the _if_ statement to ```False```.
```python
def atr(..., **kwargs):
    # ...

    if False: # Imports["talib"]:
        from talib import ATR
   ...
```
or rip out that _if-else_ block.

<br/>


Optionable
---
Alternatively, you can make it optionable with _kwargs_:
```python
def atr(..., **kwargs):
    # ...

    if Imports["talib"] and kwargs.pop("talib", False):
        from talib import ATR
   ...
```

this will allow you to call it like so:
```python
# Runs without talib since the kwarg is False by default
df.ta.atr(length=14, mamode="sma", append=True)
df.ta.atr(length=14, mamode="ema", append=True)
df.ta.atr(length=14, mamode="wma", append=True)
df.ta.atr(length=14, mamode="rma", append=True)

# Runs talib's atr
df.ta.atr(length=14, talib=True, append=True)
```

<br/>

Lastly, [here](https://github.com/twopirllc/pandas-ta/search?q=if+Imports%5B%22talib%22%5D%3A) is the current list of indicators that use TA Lib if it is installed. Similar modifications will need to be made them if needed for the time being.

Apologies for the inconvenience.

Kind Regards,
KJ

**Comment by Khunaus** [comment]
Thanks for the prompt reply and resolution.  i've updated the fix as per the Optionable version and its now working well and as expected.

Many thanks and will look out for an update in due course.

Cheers

**Comment by twopirllc** [comment]
@Khunaus,

No worries. Thanks for responding promptly as well. Glad the options worked for you. I will let you know when a permanent solution is implemented.

Thanks,
KJ
