### ISSUE TITLE
ta.vp() is not in the ta.strategy() results

### ISSUE THREAD

**Issue by reza1615** [twopirllc/pandas-ta#332]
When I run the below code
```
import pandas_ta as ta
df.ta.strategy()
```
ta.vp() columns are not in the finall result

**Comment by twopirllc** [comment]
Hello @reza1615,

That is correct. Volume Profile **vp** does not return a DatetimeIndex Time Series. Please see the _Sources_ section under ```help(ta.vp)``` to understand how it calculated and see examples of output from those sources. Furthermore, please see Issue #74 on how to plot it.

```python
vpdf = df.tail(30) # Take the last 30 Bars
vpo = vpdf.ta.vp(sort_close=True)
vpo
```

Default Output:
<img width="479" alt="Screen Shot 2021-07-07 at 4 14 17 PM" src="https://user-images.githubusercontent.com/18198392/124839855-78a55680-df3e-11eb-9a80-42edbd3432d1.png">

If you know how to add it to the original DataFrame ```df``` so that ```df.ta.strategy()``` can apply it, let's discuss it or perhaps make a Pull Request demonstrating the process. 😎 

Kind Regards,
KJ
