### ISSUE TITLE
choppiness index has different result vs trading view

### ISSUE THREAD

**Issue by mhgutier** [twopirllc/pandas-ta#348]
Hi guys good day.
im encountering 2 isues. please advise. 

1.  **kwargs is not defined. 
```python
 df['chop'] = ta.chop(df['high'], df['low'], df['close'], length=28, atr_length=None, ln=None, scalar=None, drift=None, offset=0, **kwargs)
```

```sh
NameError: name 'kwargs' is not defined
```

2. choppiness index has different result with trading view (if **kwargs is not passed as it is issue no.1)

**Comment by twopirllc** [comment]
Hello @mhgutier,

* I fail to see how the first Pull Request #1 has **any** relevance to ```ta.chop```. Please clarify.
* The ```NameError``` is a Python error and **not** a Pandas TA Error. You received that Error because you have not declared the dict ```kwargs``` prior to calling ```ta.chop()```. See ```help(ta.chop)``` for which arguments and keyword arguments are valid for ```ta.chop()```. Python Documentation on [arguments and keyword arguments](https://docs.python.org/3/glossary.html#term-argument) and [here](https://www.educative.io/edpresso/what-are-keyword-arguments-in-python) for more detailed explanation and examples.
* Have you tried any other variations of arguments and values for ```ta.chop()``` as ```help(ta.chop)``` lists?
* Have you looked up old Issues like #214 before making this Issue? If so, did it not resolve your Issue? If not, then you need a correlation test as requested on the README before I investigate this Issue again.

<img width="627" alt="Screen Shot 2021-07-18 at 7 53 37 AM" src="https://user-images.githubusercontent.com/18198392/126072001-d9de2850-d627-419f-a7c0-176e51aed8cc.png">


### How to do a TV Correlation Test

Are you using a different data source for Pandas TA and then visually comparing the numbers displayed from TradingView? If so, then that can cause deviations in calculation because they are **not** the same data source. You can **Export Chart Data** from TradingView data for comparison by using the _hamburger menu_ in the upper left corner; select the ISO format.

<img width="342" alt="Screen Shot 2020-09-02 at 7 54 25 AM" src="https://user-images.githubusercontent.com/18198392/91999924-ca170080-ecf1-11ea-911f-c73dabe9ed13.png">

Once you have exported your chart data from TradingView, try the following:
```python
import pandas as pd
import pandas_ta as ta

# Load the TV export data or whatever you saved it as
data = pd.read_csv("path/to/tradingview_data.csv") 
data.ta.chop(length=14, append=True)
# data.drop()   # https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html
print(data.corr()) # Check their correlation
```

Also please reply to this Issue with your results **and** exported TV CSV so I can see your correlations and double check your results. You may need to drop some columns before running ```data.corr()``` so it's not filled with extraneous columns.

For future bugs, remember to use a common data source when comparing indicator results, double check the documentation and/or the code for alternative versions, provide correlation results and test data.

Kind Regards,
KJ

**Comment by mhgutier** [comment]
hi Kevin, Thanks

i got choppiness index working fine now.
1. i updated the formula
from: (npLog10(atr_sum) - npLog10(diff)) / npLog10(length)
to: npLog10(atr_sum / diff) / npLog10(length)

2. atr has discrepancy from talib when timeperiod is 1
import talib
    '# atr_ = atr(high=high, low=low, close=close, length=atr_length)'
    atr_ = talib.ATR(high=high, low=low, close=close, timeperiod=atr_length).

got everything working and in sync with trading view now.

ps: im not able to generate correlation since im not subscribed in trading view. also im getting my data from binance,
ohclv is same with trading view so i dont think the issue is with the deviation in values.

Pandas_ta is really awesome. im using talib previously, now im gonna utilize pandas_ta

![image](https://user-images.githubusercontent.com/80815775/126099243-ee3b9bcf-c513-4441-8e66-047a122605fe.png)

**Comment by twopirllc** [comment]
Hello @mhgutier,

Great!

1. Out of curiosity, is the Logarithm Division Property (```log(A/B) = log(A) - log(B)```) not valid in the code?
2. Interesting. Unfortunately, I can not replicate your discrepancy with TA Lib. Can you provide reproducible code?

```sh
Out[9]: 
                 open       high  ...    ATRr_1  TAL_ATR_1
date                              ...                     
2020-09-30  10.000000  11.410000  ...       NaN        NaN
2020-10-01   9.690000  10.100000  ...  0.870001   0.870001
2020-10-02   9.060000   9.280000  ...  0.520000   0.520000
2020-10-05   9.430000   9.490000  ...  0.570000   0.570000
2020-10-06   9.040000  10.180000  ...  1.280001   1.280001
...               ...        ...  ...       ...        ...
2021-07-15  21.719999  22.055000  ...  1.045000   1.045000
2021-07-16  21.600000  21.709999  ...  0.469999   0.469999
2021-07-19  20.969999  21.690001  ...  1.140001   1.140001
2021-07-20  21.629999  22.350000  ...  1.130001   1.130001
2021-07-21  22.270000  22.680000  ...  0.559999   0.559999

[203 rows x 7 columns]
```

> got everything working and in sync with trading view now.

Excellent!

> ps: im not able to generate correlation since im not subscribed in trading view. also im getting my data from binance, ohclv is same with trading view so i dont think the issue is with the deviation in values.

Ok

> Pandas_ta is really awesome. im using talib previously, now im gonna utilize pandas_ta

Thanks! Cool! 😎 

Sorry I did not respond sooner, was sick the last few days.

Kind Regards,
KJ
