### ISSUE TITLE
Indicator Request - Connors RSI (CRSI)

### ISSUE THREAD

**Issue by crazysurajit** [twopirllc/pandas-ta#349]
Hi @twopirllc ,
Could you please add the Connors RSI (CRSI) indicator?

[About CRSI](https://www.tradingview.com/support/solutions/43000502017-connors-rsi-crsi/)
[Code for reference](https://github.com/cperler/trading/blob/1da33afc28d77517ee803ddfc1a1126dcdd54a3a/indicators.py#L695)

Also doc for [Aroon](https://github.com/twopirllc/pandas-ta/blob/1deb7559f626d2a5cf664b6c0af7a8016a53bfca/pandas_ta/trend/aroon.py#L94) is not reflecting its current arguments: high, low

**Comment by twopirllc** [comment]
Hello @crazysurajit,

Unfortunately, I am backlogged on many Issues right now. Hopefully someone can attempt it soon for you.

Kind Regards,
KJ

**Comment by Joy2489** [comment]
Yes

**Comment by rengel8** [comment]
Hey @Joy2489,
I stumbled over CRSI a few times in the past and did implement a **streak** indicator, which is the only missing building block for Pandas TA, if I understood the provided calculation correctly.

**The code is here:**
[streak indicator](https://github.com/rengel8/pandas-ta/blob/streak/pandas_ta/trend/streak.py)

```Python
df['streak'] = ta.streak(close=df["close"])

df['first-rsi'] = ta.rsi(close=df["close"], length=14)
df['second-rsi'] = ta.rsi(close=df["streak"], length=2)
df['roc'] = ta.roc(close=df["close"], length=100)

df['crsi'] = (df['first-rsi'] + df['second-rsi'] + df['roc']) / 3
````
Some feedback on this would be helpful. I think, that CRSI is rather choppy and will tend to produce lots of signals depending on the way one uses it.

**Comment by Joy2489** [comment]
@crazysurajit

**Comment by crazysurajit** [comment]
Thank you @rengel8 for providing an implementation.
Haven't tested it yet, however just by going over the code it looks correct.

Also I think according to [Calculation](https://www.tradingview.com/support/solutions/43000502017-connors-rsi-crsi/) the RSI length is 3

`df['first-rsi'] = ta.rsi(close=df["close"], length=3)`

**Comment by crazysurajit** [comment]
Tried to plot the CRSI of ^GSPC (for last 90 days with 1 day freq), but for some reason the graph looks different from what appears on TradingView
![Figure_1](https://user-images.githubusercontent.com/12027492/132831460-27d4400d-bfce-4f15-9824-7d0afe6bf001.png)

**Comment by crazysurajit** [comment]
Tried to plot the CRSI of ^GSPC (for last 90 days with 1 day freq), but the graph looks different from what appears on TradingView, might be due to differences in Price data from Yahoo Finance.
![SPX_2021-09-11_07-50-13](https://user-images.githubusercontent.com/12027492/132921393-4708139f-8da6-413b-9cb8-976cedef0f8d.png)
```
streak = ta.streak(close)
rsi1 = ta.rsi(close, length=3)
rsi2 = ta.rsi(streak, length=2)
roc = ta.roc(close, length=100)
df['CRSI_3_2_100'] = (rsi1 + rsi2 + roc) / 3
```
![Figure_1](https://user-images.githubusercontent.com/12027492/132921143-45416f4a-89e6-4a82-9255-279c57fc657a.png)

**Comment by crazysurajit** [comment]
Not sure if this would be acceptable as a less time overhead option
```
    # Calculate Result
    prior_value = 0
    prev_close = close.iloc[0]
    for i in range(1, close.size):
        curr_close = close.iloc[i]
        if curr_close > prev_close:
            if prior_value < 0:
                result[i] = 1
            else:
                result[i] = prior_value + 1
        elif curr_close < prev_close:
            if prior_value < 0:
                result[i] = prior_value - 1
            else:
                result[i] = -1
        else:
            result[i] = 0

        prev_close = curr_close
        prior_value = result[i]
```

**Comment by gosharevo** [comment]
Hi @rengel8 @crazysurajit. How you use ta.streak fucntion? I get  

> `AttributeError: module 'pandas_ta' has no attribute 'streak'`

**Comment by crazysurajit** [comment]
> Hi @rengel8 @crazysurajit. How you use ta.streak fucntion? I get
> 
> > `AttributeError: module 'pandas_ta' has no attribute 'streak'`
Please add below in `trend/__init__.py` file
`from .streak import streak`

**Comment by gosharevo** [comment]
@crazysurajit  
![image](https://user-images.githubusercontent.com/52243293/154642612-ede80764-0a30-44bc-98fa-a92671c9a5d8.png)

**Comment by hayesfj** [comment]
@gosharevo 
I am having the same issue with ".streak import streak".   Where you ever able to resolve it?

**Comment by char101** [comment]
Example implementation of connors rsi:

```python
import pandas as pd


def rsi(close, period):
    delta = close.diff()
    up = delta.clip(lower=0).ewm(alpha=1 / period).mean()
    down = delta.clip(upper=0).abs().ewm(alpha=1 / period).mean()
    return 100.0 - (100.0 / (1.0 + up / down))


def streaks(close):
    def consecutive_count(b):
        cs = b.astype(int).cumsum()
        return cs.sub(cs.mask(b).ffill())

    prev = close.shift()
    return consecutive_count(close > prev) - consecutive_count(close < prev)


def percent_rank(close, lookback):
    return close.pct_change().rolling(lookback).apply(lambda s: (s.iloc[1:] < s.iat[0]).sum() / lookback)


def connors_rsi(close, rsi_period=3, streaks_period=2, percent_rank_period=100):
    return (rsi(close, rsi_period) + rsi(streaks(close), streaks_period) + percent_rank(close, percent_rank_period)) / 3
```

**Comment by hayesfj** [comment]
Thank you for the example.

Frank

**Comment by luisbarrancos** [comment]
@twopirllc , I'm working on this, but just to confirm, According to the CRSI [authors](https://alvarezquanttrading.com/blog/connorsrsi-analysis/?unapproved=1796&moderation-hash=ab719add6a43855e89ba4a2ee8c4d5b7#comment-1796), in [An Introduction to the ConnorsRSI](https://alvarezquanttrading.com/wp-content/uploads/2016/05/ConnorsRSIGuidebook.pdf), the RSI used is not the standard RSI with a simple moving average alone, but Wilder's RSI using the Wilder's smoothing function as a dampening factor, as implemented in *New Concepts in Technical Trading Systems*, ISBN 0-89459-027-8, page 65, *Dampening Steps* 1, 2, 3.

It's similar to an exponential moving average but with a $\frac{1}{period}$ weight, which seems to be the RSI implementation implemented in Pandas-TA, using the [*RMA* moving average](https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/overlap/rma.py#L13). Are you ok with editing the RSI indicator as well such that the documentation in *Sources* [here](https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/momentum/rsi.py#L30) states, besides the given TV reference, the most authoritative source(s) as well, Wilder's book, ISBN, page if needed, since this source is clearer about the *smoothing function* ?

**Comment by luisbarrancos** [comment]
I should add this rather than on the [pull request](https://github.com/twopirllc/pandas-ta/pull/737)  since there seems to be some confusion as to how the *percent rank* is calculated.
According to the original author:

> The final component of the ConnorsRSI looks at the size of today's price change in relation to previous price changes. We do this by using a Percent Rank calculation, which may also be referred to as a percentile. Basically the percent rank value tells us the percentage of the values in the look-back period that are less than the current value.
> 
> For this calculation we measure price change not in dollars and cents, but as a percentage of the previous day's price.
> This percentage gain or loss is typically referred to as the one-day return. Fo if yesterday's closing price was $80.00 and today's price is $81.60, the one-day return is ($81.60 - $80.00) / $80.00 = 0.02 = 2.0%
> 
> To determine the percent rank we need to establish a look-back period. The percent rank value is then the number of values in the look-back period that are less than the current value, divided by the total number of values. 

In particular, emphasis mine:

> For example, **if the look-back period is 20 days, then we would compare today's 2.0% return to the one-day returns from each of the previous 20 days**.  

This means, for example, starting at $t=1$, for a *lookback* period of 20 days, the current value is by definition $t=21$, and we will be comparing the current return, from day 20 to day 21 or $R_{21}$ with the 19 returns from the preceding 20 days. The number of returns to compare against must be $lookback - 1$.
We are looking back $n$ days, not $n$ daily change values, that is clearly indicated.

I'll add that in the PR i was concerned with implementing the indicator according to the most authoritative source, the original authors. The behaviour(s) of other platforms, such as TV, is something that i can replicate as well, and if it differs, we can add a optional flag ```tvmode: bool```  like what was done for the [Chande-Kroll stop](https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/trend/cksp.py#L18) indicator.

**Comment by luisbarrancos** [comment]
@twopirllc this issue can be closed, solved by [this PR](https://github.com/twopirllc/pandas-ta/pull/737).

**Comment by twopirllc** [comment]
Hi @crazysurajit, @rengel8, @char101,

**CRSI** is now available on the _development_ branch. Thank you @luisbarrancos 
Reopen if there are any issues.

KJ

**Comment by luisbarrancos** [comment]
@char101 notice you will get different results, since the implementation you pasted was diverging from the official indicator, in that you were comparing the 1st day in the lookback period against the suceeding days, rather than the last most current day in the lookback period, against the preceding days.
```python
def percent_rank(close, lookback):
    return close.pct_change().rolling(lookback).apply(lambda s: (s.iloc[1:] < s.iat[0]).sum() / lookback) * 100.0
```
The ```s.iloc[1:]``` slice is a list from 1st element onwards, not inclusive, while ```s.iat[0]``` is the 1st element, which will be compared against each of the preceding slice.
The implementation of this indicator follows the original author's implementation to the letter. References are in the source code.
