### ISSUE TITLE
SuperTrend indicator is incorrect

### ISSUE THREAD

**Issue by maxmahbk** [twopirllc/pandas-ta#357]
I compare supertrend indicator in pandas-ta and trading view is different.

in pandas_ta is likely signal change when price drop below or increase above ST value  SUPERT_10_3.0

in trading view price close need to lower or above ST value to change signal trend buy -> sell.

![ST](https://user-images.githubusercontent.com/70783418/127159258-e9cf8e25-7efb-4545-b976-a97dda621612.JPG)

BTC/USD 15min TF in indicator from ST seen more altered of signal then in real graph.

Thank

**Comment by maxmahbk** [comment]
![image](https://user-images.githubusercontent.com/70783418/127160286-ee1d79f3-4172-4799-8e53-627d7df57419.png)

Signal from tradingview not change if close price not below the lower ST band.

Could you have an more option for supertrend indicator.

Thank you

**Comment by twopirllc** [comment]
Hello @maxmahbk,

So what version of Pandas TA are you using that was asked in the Bug Report?

Your full screenshot in the first post with the data is unreadable... share it as a csv, no excel.

Did you read the README? Did you look up past Issues first?  

<img width="587" alt="Screen Shot 2021-07-27 at 7 56 49 AM" src="https://user-images.githubusercontent.com/18198392/127177376-5d40cf4a-f308-4965-9332-74b9a4654747.png">

Where is your correlation test results from using TradingView Data and TradingView's SuperTrend?

### How to do a TV Correlation Test

Are you using a different data source for Pandas TA and then visually comparing the numbers displayed from TradingView? If so, then that can cause deviations in calculation because they are **not** the same data source. You can **Export Chart Data** from TradingView data for comparison by using the _hamburger menu_ in the upper left corner; select the ISO format.

<img width="342" alt="Screen Shot 2020-09-02 at 7 54 25 AM" src="https://user-images.githubusercontent.com/18198392/91999924-ca170080-ecf1-11ea-911f-c73dabe9ed13.png">

Once you have exported your chart data from TradingView, try the following:
```python
import pandas as pd
import pandas_ta as ta

# Load the TV export data or whatever you saved it as
data = pd.read_csv("path/to/tradingview_data.csv") 
data.ta.chop(length=14, append=True)
# data.drop()   # https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html
print(data.corr()) # Check their correlation
```

Also please reply to this Issue with your results **and** exported TV CSV so I can see your correlations and double check your results. You may need to drop some columns before running ```data.corr()``` so it's not filled with extraneous columns.

For future bugs, remember to use a common data source when comparing indicator results, double check the documentation and/or the code for alternative versions, provide correlation results and test data.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@maxmahbk,

### Correlation of TV and Pandas TA Supertrend Up/Down Trends
I used SPY Daily Data with over 

```python
def highlight_top(s, v=0.98):
    return ["background-color: lightgreen" if cell else "" for cell in s > v]

df = # Your TradingView ohlcv + supertrend indicator data
df.set_index(pd.DatetimeIndex(df["time"]), inplace=True, drop=True)
df.ta.supertrend(length=10, append=True)

# Drop unnecessary columns to make correlation table easier to compare
df.drop(["time", "oc2", "TV_CRSI_3_2_100", "SUPERT_10_3.0", "SUPERTd_10_3.0"], axis=1, errors="ignore", inplace=True)
df = df[df.columns[4:]]

print(f"Total bars: {df.shape[0]}")
stcorr = df.corr()
stcorr.style.apply(highlight_top)
```

#### Result
<img width="486" alt="Screen Shot 2021-07-29 at 9 46 15 AM" src="https://user-images.githubusercontent.com/18198392/127532129-fb282f0a-0035-4c09-9314-f416696cf41c.png">

<br/>

With well over 7000 data points and nearly 1-1 correlation for both Up and Down Trends, I feel that is pretty sufficient. Don't forget we are also comparing Python, a language, vs Pinescript, a scripting language, so there is at times deviation. If it is insufficient for you, feel free to fork, edit, and submit a Pull Request so that all users may benefit with improved accuracy. Contributions are welcome! 😎

Thanks,
KJ

**Comment by maxmahbk** [comment]
My apologies for the delay after i update pandas_ta to lastest version it work correctly about signal. previously i try update many times but it not work so i stop update for 2-3 months

Thank you very much.

**Comment by twopirllc** [comment]
@maxmahbk,

No worries. Glad it is resolved.

Thank you for the donation! ☕ 
KJ
