### ISSUE TITLE
alma doesnt work with multi core processing

### ISSUE THREAD

**Issue by reza1615** [twopirllc/pandas-ta#366]
when I run alma with different variables it doesn't work under multi processors. for the rest of the indicators, it is ok.

**Comment by twopirllc** [comment]
Hello @reza1615,

Which Pandas TA version? Where is your minimal reproducible code?

Thanks,
KJ

**Comment by reza1615** [comment]
version 0.3.14b0

```python

for strategy in ['alma']:
  ta_list=[
  {"kind": strategy,  "prefix":f"foo@"}
  ]
  df.ta.cores = 31
  df.ta.strategy(ta.Strategy(
              name=f"{strategy}",
              description=f"{strategy}",
              ta=ta_list
          ),timed=True)
```

**Comment by twopirllc** [comment]
@reza1615,

> when I run alma with different variables it doesn't work under multi processors

Working code:
```python
df = # your ohlcv
ta_list=[{"kind": "alma", "sigma": 3.5, "distribution_offset": 0.78, "prefix":f"foo@"}]
almastrat = ta.Strategy(name=f"Alma", description=f"Alma", ta=ta_list)

df.ta.strategy(almastrat, cores=0, timed=True) # Few indicators => set cores = 0
print(df)
```
Where is your code supporting your claim "different variables it doesn't work under multi processors"?

<br/>

Second, you only need to set ```cores``` and ```ta_list``` once, not for each call of the _for_ loop.

Last if you only have a **few** indicators, naturally _multiprocessing_ will be slow since the OS has to spin up a processing pool prior to execution. So in this case, you should set ```df.ta.cores = 0```. For more information, read PR #199.

Kind Regards,
KJ
