### ISSUE TITLE
How to just calculate the last value of indicators rather than from the begin to the end

### ISSUE THREAD

**Issue by 630362055** [twopirllc/pandas-ta#389]
ema(close,length=10)
When I do live trading, I already have 10 data points. Did the ema calculate it only once, or did the ema do it for all the previous 9 data

**Comment by twopirllc** [comment]
Hello @630362055,

In your case, it uses the full length of 10.

Unfortunately there are no _incremental computations_ in the library yet. However contributions to add that functionality are accepted. 😎  For more information, please see Issues #87 and #288 where this has been previously discussed.

Kind Regards,
KJ

**Comment by AGG2017** [comment]
When backtesting, we often need the same indicators to be recalculated again and again over the same data, and if the indicators are not that simple like ema, my best solution was to redo some slow indicators by adding file caches for data + parameter signatures because df.to_pickle/read_pickle are much faster than most of the indicator calculations.
