### ISSUE TITLE
[bug] the ATR func use the RMA calc

### ISSUE THREAD

**Issue by homily** [twopirllc/pandas-ta#39]
@twopirllc Thanks for creating this wonderful python module. 
I'm extensively using this module for my algos.

when i use the ATR func,the return different with tradingvew.
it mabe use rma to calc.
so the ATR=RMA(TA,lengh)

can you update it? Thanks !

**Comment by twopirllc** [comment]
Hello @homily,

Thanks for using the module.  I'll take a look at it when I get a chance.

Also there will likely be differences with TradingView to a minor degree since they are using their proprietary Pinescript language, which is likely Javascript and not Python nor C.  I test the indicators against those that exist in the industry standard [TA Lib](http://ta-lib.org/).

Thanks

**Comment by homily** [comment]
ok, thanks
