### ISSUE TITLE
can't save Bolinger Band return values or supertend return values

### ISSUE THREAD

**Issue by hanging-man** [twopirllc/pandas-ta#391]
I was using an older version of your panda_ta 
I could save bolinger band return values as 
d1['BBL'] = d1.ta.bbands().fillna(0).BBL_20.round(4)
d1['BBM'] = d1.ta.bbands().fillna(0).BBM_20.round(4)
d1['BBU'] = d1.ta.bbands().fillna(0).BBU_20.round(4)
yesterday I upgraded to latest panda_ta
I see that return values now have identifiers as BBL_5_2.0  BBM_5_2.0    BBU_5_2.0  (i.e. with a 2.0 at the end)
now when I am trying to save it as
  d1['BBM'] = d1.ta.bbands().fillna(0).BBM_5_2.0
I am getting the following error 

    d1['BBM'] = d1.ta.bbands().fillna(0).BBM_5_2.0
                                                 ^
SyntaxError: invalid syntax

I am a novice learner of python so I am not sure I have managed to explain the issue. Hope you would be able to help. 
Thanks.

**Comment by twopirllc** [comment]
Hello @hanging-man,

I see. The floating point name is making it difficult. You are welcome to fork and edit the **bbands** return names so it doesn't show standard deviations in floating point. If not, that's understandable. Perhaps some code below can be of use instead of:

```python
d1['BBL'] = d1.ta.bbands().fillna(0).BBL_20.round(4)
d1['BBM'] = d1.ta.bbands().fillna(0).BBM_20.round(4)
d1['BBU'] = d1.ta.bbands().fillna(0).BBU_20.round(4)
```

There are a couple of things we can do to improve your original code above. First it is make three separate calls to **bbands** which is what I was trying  to avoid by having **bbands**, **supertrend**, et al other indicators that return [Pandas DataFrames](https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html). You only need to call **bbands**, **supertrend**, et al once. Below are three other ways of accomplishing what you described.

### **(A)** Manually rename and append to the DataFrame
```python
df1 = # ohlcv data

# Returns a DataFrame called bbdf with all the bband columns, fills nas to 0 and rounds to 4
bbdf = d1.ta.bbands(fillna=0).round(4)

# Rename and add the columns to d1 like before
d1['BBL'] = bbdf[bbdf.columns[0]]
d1['BBM'] = bbdf[bbdf.columns[1]]
d1['BBU'] = bbdf[bbdf.columns[2]]
```

### **(B)** Use the DataFrame Extension "ta" to append, then rename and drop columns
```python
df1 = # ohlcv data
d1.ta.bbands(fillna=0, append=True).round(4)
# Removes "BBB_5_2.0" and "BBP_5_2.0", the last 2 columns, from the DataFrame
d1 = d1.iloc[:,:-2] 
d1.rename(columns={"BBL_5_2.0": "BBL", "BBM_5_2.0": "BBM", "BBU_5_2.0": "BBU"}, inplace=True)
```

### **(C)** Use the ```df.ta.strategy()``` method to apply and rename, then drop last 2 cols
```python
df1 = # ohlcv data

# Define a Strategy with parameters
bbs = ta.Strategy(name="Hanging Man BBs",
    ta=[{
        "kind": "bbands", "fillna": 0,
        "col_names": ("BBL", "BBM", "BBU", "BBB", "BBP")  # Rename columns
    }]
)
# Set cores=0 since not enough indicators to warrant Multiprocessing
d1.ta.strategy(bbs, cores=0, verbose=False)
# Removes "BBB" and "BBP", the last 2 columns, from the DataFrame
d1 = d1.iloc[:,:-2]
```

Let me know if this helps.

Kind Regards,
KJ

**Comment by hanging-man** [comment]
Thank you for giving me such a detailed explanation of this issue that I highlighted. 
I really appreciate you taking so much time to explain. 
I will attempt to make the necessary changes. 
Thanks again.

**Comment by twopirllc** [comment]
@hanging-man,

No worries. Hope it helps and makes sense.

KJ
