### ISSUE TITLE
Panda-ta's VPVR shows diff. result 

### ISSUE THREAD

**Issue by pwnedDesal** [twopirllc/pandas-ta#398]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
0.3.30b0
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
I have used the same time frame here, and the same start and end date, and Exchange(binance), and same numbers of columns. Here the .csv file of ohlcv starting from January 21 2021 [BTC-USDT.csv](https://github.com/twopirllc/pandas-ta/files/7243057/BTC-USDT.csv).
**Python code that shows VPVR of BTC-USDT 
```python
import pandas as pd
import numpy as np
from scipy import stats, signal
import plotly.express as px
import plotly.graph_objects as go
import pandas_ta as ta
# Fetch OHLCV data
data = pd.read_csv('ohlcv/BTC-USDT.csv')
vp=ta.vp(data['close'],data['volume'],24)
# Set the index to mean_close and in ascending order
vp['mean_close'] = round(vp['mean_close'], 2)
vp.set_index('mean_close', inplace=True)
vp.sort_index(ascending=True, inplace=True)
#print("Sorted by mean_close\n", vp, "\n") # Visual Table Check
# Take the last three columns and plot them with horizontal bars
vp[vp.columns[-3:]].plot(
    kind='barh', 
    figsize=(5, 8),
    title="BTCUSDT",
    color=['green', 'red', 'silver'],
    alpha=0.45,
    stacked=True,
)
```
** Screenshoots of pandas-ta shows 46k has the highest volume** 
![image](https://user-images.githubusercontent.com/6646675/135070142-cf531c2d-6510-45e0-bec1-b4d56839a8df.png)
while on tradingview 34k is the highest value 
![image](https://user-images.githubusercontent.com/6646675/135070262-ace85760-6aeb-4abe-9c35-33a082e8c3b9.png)

**Comment by twopirllc** [comment]
Hello @pwnedDesal,

> I have used the same time frame here, and the same start and end date, and Exchange(binance), and same numbers of columns. Here the .csv file of ohlcv starting from January 21 2021.

Thanks for providing the CSV, code and screenshots. 😎  The results do look different, but I anticipated that since TradingView (TV) does _not_ provide any PineScript code for any of their Volume Profiles (VPs) to cross-reference nor can one export the data with VP columns to numerically compare. Unfortunately to align Pandas TA's VP to TradingView may take some time given the lack to information mentioned and the current load of unresolved issues. 😞 

I am curious about your results if you tried the ```sort_close=True``` [kwarg](https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/volume/vp.py#L14) instead for **vp** with the same data.

```python
# Instead of:
vp=ta.vp(data['close'],data['volume'],24)

# Try:
vp=ta.vp(data['close'],data['volume'], 24, sort_close=True)
```

Kind Regards,
KJ

**Comment by pwnedDesal** [comment]
Thanks, this is quite aligned now, and you may also take a look at [kv4coins](https://www.tradingview.com/script/r3VrWAO4-Volume-Profile/) volume profile code for reference, which include PoC as well

**Comment by twopirllc** [comment]
@pwnedDesal,

Excellent! Glad that option added by @delicateear meets expectations. Also, thanks for sharing the link for PoC code. 😎 

Thanks,
KJ

**Comment by knucklesuganda** [comment]
The results are different because of the formula that is used. It goes like that: if the candle is red, then count everything as sell, and count everything as buy otherwise. It should look for the real sell and buy orders, instead of the candle type. I will make another indicator with a pull request

**Comment by tcnoff** [comment]
> The results are different because of the formula that is used. It goes like that: if the candle is red, then count everything as sell, and count everything as buy otherwise. It should look for the real sell and buy orders, instead of the candle type. I will make another indicator with a pull request

Curious did you ever get this working to match TV results?
