### ISSUE TITLE
Issue with reults of rma moving average

### ISSUE THREAD

**Issue by mihakralj** [twopirllc/pandas-ta#402]
**Describe the bug**
ta.rma() should behave exactly like ta.ema() - with the only difference being the weighting factor.
Implementation of ta.rma() in pandas_ta calculates the starting value differently than the implementation of ta.ema()
specifically, **the first value** in the ta.rma() result should be a SMA() average of the period. If the first value is different, the whole series is different...

**To Reproduce**
```python
df = pd.DataFrame({'close': [1.0,0,-1,0,2,-3,4,5,-8,7,8,9,10,-5,10,0]})
df["rma"]=df.ta.rma(close=df["close"], length=4)
df["ema"]=df.ta.ema(close=df["close"], length=4)
```
the first value that is not a NaN should be the same for both rma() and ema() - but it is not...

**Comment by twopirllc** [comment]
Hello @mihakralj,

I wouldn't consider this a bug, rather an optional enhancement request.

If it were truly a **bug**, I would have also received bug Issues from other indicators that rely on **rma** such as **adx**, **cmo**, **kdj**, **qstick**, and **rsi** and that they do not correlate with either TA Lib, TradingView or some other trading platform. But since those dependent indicators are passing such correlation tests, then **rma** is not bugged.

I also want to point out that there are _no_ standards regarding Technical Indicators. Different trading platforms bootstrap and initialize indicators differently for various reasons. Even the _de facto_ TA Lib mentions this in some of their comments for some indicator calculations. For instance, consider TA Lib's **EMA** comment:

```c
/* The first EMA is calculated differently. It
* then become the seed for subsequent EMA.
*
* The algorithm for this seed vary widely.
* Only 3 are implemented here:
*
* TA_MA_CLASSIC:
*    Use a simple MA of the first 'period'.
*    This is the approach most widely documented.
*
* TA_MA_METASTOCK:
*    Use first price bar value as a seed
*    from the begining of all the available
*    data.
*
* TA_MA_TRADESTATION:
*    Use 4th price bar as a seed, except when
*    period is 1 who use 2th price bar or something
*    like that... (not an obvious one...).
*/
```

<br/>

As you can imagine, this is problematic. Luckily, Pandas TA is Open Source and open to contributions to the library, like your implementation of **jma**. If you want to include code that solves: "the first value that is not a NaN should be the same for both rma() and ema()", please submit a PR but please keep the current functionality as the default. 😎 

Kind Regards,
KJ

**Comment by mihakralj** [comment]
Sounds good. 😊 I did find this discrepancy by getting different data from ATR (average true range) compared to the official example by J. Wilder (the author of both ATR and RMA). Let's keep the library as it is then, if all other rma-derived indicators are satisfactory for library users. I would not mess with adding another parametric option to make the indicator following the author's original formula, let's keep the current simplified version.

**Comment by twopirllc** [comment]
Yeah. Thanks for looking out though. 😎

**Comment by mihakralj** [comment]
I was reading the original works of Welles Wilder and got across his ATR chapter. It reminded me of this issue I opened a year ago. If you are looking at Welles' example and try to reproduce it with Pandas-TA, you get discrepancy:

df = pd.DataFrame({'close': [1.4,1.5,1.4,1.4,1.3,1.7,1.2,0.7]})
df["rma"]=df.ta.rma(close=df["close"], length=7)
Last two results - according to the source - should be **1.41** and **1.31**
Pandas-TA returns 1.406 and 1.264

Current implementation of RMA (and therefore ATR and all other RMA-related indicators in Pandas-TA) is flawed for early data. Due to exponentially self-correcting nature of the formula, results of true and flawed algo will converge after 30+ bars - it is only the early data that is impacted.

This is the picture from Weller Wilder's original book explaining ATR (and implicitly explaining RMA):

![image](https://user-images.githubusercontent.com/31756078/163031211-e3b8b4c7-b453-464a-b561-44171ca2b89e.png)

**Comment by twopirllc** [comment]
@mihakralj,

Oh! Thanks for sharing! This is great! 

If you want to give it a crack, checkout the _developement_ branch and submit a PR. 😎 

KJ

**Comment by twopirllc** [comment]
@mihakralj,

So it appears that there is a calculation mistake of the Range on 1/6. Instead of _1.70_, it should be _1.80_ which alters the initial sum to be _10_ instead of _9.90_. So the SMA for the 1st ATR should be _10/7 ≈ 1.428571_. Not the bug I was hoping to encounter while I fix **rma** but also some minor modifications to **true_range** and **atr** as well. Anyhow, here are the PTA results for Welles Wilder table from his book:

<img width="424" alt="Screen Shot 2022-04-21 at 9 31 51 AM" src="https://user-images.githubusercontent.com/18198392/164508766-1935724b-89f2-4c55-b203-59a60274c49b.png">

<br/>

Thanks for sticking to this issue and providing raw documentation on the source (very helpful!).

KJ

**Comment by mihakralj** [comment]
Yup, can confirm that you found the data bug in a 42-years old book! :-)
Below is the calc of TR and ATR for the same raw data from the book using my C# lib:

![image](https://user-images.githubusercontent.com/31756078/164513936-e939397c-3b37-4e36-971f-6a2c88d084ec.png)

**Comment by twopirllc** [comment]
@mihakralj 

Lol! 🤣 That would've been nice to have sooner as well.

Thank you for confirmation.

**Comment by mihakralj** [comment]
Just checking if this fix was merged into the main build yet?

**Comment by twopirllc** [comment]
@mihakralj,

The _main_ branch is on hold for the time being until I complete the Hilbert Transform TA Lib indicators: *ht_dcperiod, ht_dcphase, ht_phasor, ht_sine, ht_trendline, ht_trendmode*.

The changes in this issue have been made and are available on the _development_ branch. 

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Mind rechecking your results using the _development_ version instead?

Thanks
KJ
