### ISSUE TITLE
Set up automatic code-coverage reporting

### ISSUE THREAD

**Issue by VFermat** [twopirllc/pandas-ta#423]
**Which version are you running? The lastest version is Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We should add an automated coverage checker, to ensure the package is covered by existing tests.

**Describe alternatives you've considered**
Implementing a GitHub action using a coverage tool, such as:
- `Coverage`
- `Codecov`

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @VFermat,

Is there a good free one you would recommend? Or know any good example Actions or Workflows to achieve this?

Kind Regards,
KJ

**Comment by VFermat** [comment]
Hi @twopirllc!

Actually yes! I'm working on an [issue about code coverage](https://github.com/centerofci/mathesar/issues/603) in another repository right now.

We are using the `Coverage` module through the `pytest-cov` add-on!

It is completely free and we can automate it to run for every merged pull request.

If you want I could work on this :D

**Comment by twopirllc** [comment]
@VFermat,

Nice! That would be great! 😎 

Free coverage is desirable since this package does not even make enough in donations to even come close cover my TradingView subscription that allows cross test with their indicators. 😞 

The Pandas TA tests do require TA Lib though, so hopefully that is a non-issue. Or at least easily rectifiable.

Kind Regards,
KJ
