### ISSUE TITLE
Psar loop starting at wrong index 1

### ISSUE THREAD

**Issue by daoudjahdou** [twopirllc/pandas-ta#424]
**Pandas ta version**
```python
0.3.14b0
```

**Describe the bug**
When reviewing the code of psar (https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/trend/psar.py#L46) the loop starts at the wrong index 1, it should start at 2, (Line 46)
Because after we do this computation:
_sar = max(high.iloc[row - 1], high.iloc[row - 2], _sar)
or this one
_sar = min(low.iloc[row - 1], low.iloc[row - 2], _sar)
when row is 1 we compare high.iloc[0] and high.iloc[-1] which is the last element of the list not the previous.

**Comment by AbyssAlora** [comment]
Hi guys, few months ago I realized that as well. But as I know PSAR corrects itself after few iterations what means that it wasn't critical issue for me and I did not put much thought to it, sorry for that. 

Best regards,
AA

**Comment by twopirllc** [comment]
Hello @daoudjahdou,

It's possible that I was sloppy. 😬  I will take a look if there is any difference to the results in Issue https://github.com/twopirllc/pandas-ta/issues/180#issuecomment-860380367.  Hopefully I still have the test code used to generate TV's, TA Lib's, @AbyssAlora's, and Pandas TA's version and see how it compares when it begins at ```2``` instead of ```1``` you identified.

Do you, by chance, have any testing code similar to Issue https://github.com/twopirllc/pandas-ta/issues/180#issuecomment-860380367 that shows the difference between the initial loop value? Cause that would help also. If not, no worries.

Kind Regards,
KJ

**Comment by daoudjahdou** [comment]
If you just try to compare Pandas TA's with it self using two start indexes you'll see some differences.
In my opinion the one using 1 as a start index is wrong as it is using data from the future (`high.iloc[-1]`) regarding the index of computation, and affects next computations.

**Comment by twopirllc** [comment]
@daoudjahdou,

Oops... this is the correct _development_ branch. Improved performance, docs, typing, ....

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

KJ
