### ISSUE TITLE
Identifying ML Categorical vs Continuous Features from All Strategy

### ISSUE THREAD

**Issue by Stoner-sen** [twopirllc/pandas-ta#434]
I have collected historical stock data and use the Pandas TA AllStrategy to get features for my data. Then I will use the features generated by Pandas TA in a ML model to forecast prices. However, I need to standardize/scale the features and thus know which features are categorical and which are continuous. Is there a way to extract this information?

 In addition some of the features generated are really large (maximum value of magnitude 10^+40). I used the  Pandas TA AllStrategy as I don't have much experience with technical indicators. Is there some better method to make technical features for my data?

Thank you!

**Comment by twopirllc** [comment]
@Stoner-sen,

> However, I need to standardize/scale the features and thus know which features are categorical and which are continuous. Is there a way to extract this information?

Since Pandas is a major component of this library, you can utilize features of Pandas to accomplish task. If I understand you correctly, what you are looking for are Pandas DataFrame [dtypes](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html).

### Data Collection
In Jupyter Notebook
```python
import pandas as pd
import pandas_ta as ta

tmpdf = ta.df.ta.ticker("SPY", period="6mo")
tmpdf.drop(["Dividends", "Stock Splits"], axis=1, errors="ignore", inplace=True)
tmpdf.shape
```

### Run All Strategy
```python
df = tmpdf.copy()
df.ta.strategy()
df.shape
```

### Column Data Type
```python
pd.set_option("max_rows", 300)  # Display all the rows of dytpes
df.dtypes
```

#### Output
<img width="273" alt="Screen Shot 2021-11-23 at 2 40 37 PM" src="https://user-images.githubusercontent.com/18198392/143140425-c4871192-b077-44b3-bf3a-a767be61e9d7.png">

<br/>

From this it should be evident what sort of data types are returned; mostly _numerical_ for plotting purposes. Some indicators will include _NaN_ values which the user is required to manage themselves.... either filling them in or dropping rows that include them.

I'll answer the other questions in a separate comment.

Kind Regards,
KJ

**Comment by Stoner-sen** [comment]
Thank you! This was what I tried at first, but after studying the features more closely I was not sure anymore. F.eks should "CDL_DOJI_10_0.1" be categorical as there is only two unique values for this indicator?
![Skjermbilde 2021-11-24 kl  08 49 31](https://user-images.githubusercontent.com/60887674/143196534-86203df5-399c-4a72-aa45-780594b83e2a.png)

Also, you see from the "PVR" indicator that it only has 4 unique values but dtype is float64. Is this correct?
![Skjermbilde 2021-11-24 kl  08 51 44](https://user-images.githubusercontent.com/60887674/143196793-bf95ed74-6ed7-4d2c-940f-6db33fa94dff.png)

Kind regards

**Comment by twopirllc** [comment]
@Stoner-sen,

> should "CDL_DOJI_10_0.1" be categorical as there is only two unique values for this indicator?

Up to you to decide. A candle is either a [Doji](https://www.investopedia.com/terms/d/doji.asp) or it's not. In TA Lib a Doji (100) or not a Doji (0). There is also ```help(ta.cdl_doji)``` which is Pandas TA's implementation.

> Also, you see from the "PVR" indicator that it only has 4 unique values but dtype is float64. Is this correct?

In short, yes 4 values. Please use ```help(ta.pvr)``` to get a description and links to source.

KJ

**Comment by twopirllc** [comment]
@Stoner-sen,

Apologies for not getting back to your second block of questions sooner.

> In addition some of the features generated are really large (maximum value of magnitude 10^+40). I used the Pandas TA AllStrategy as I don't have much experience with technical indicators.

Yes, clearly the "All Strategy" is a sub-optimal approach for finding potential patterns or signals with indicators. It also appears to be the go to approach for AI/ML practitioners and enthusiasts to mine and extract some value. One could possibly use [Dimensionality Reduction Models](https://machinelearningmastery.com/dimensionality-reduction-for-machine-learning/) to help reduce the feature set, which is _subtractive_, as you know. And this would still be highly computational and reductive process. Maybe this has or does work for other AI/ML practitioners 🤷🏼‍♂️ if computational power is negligible for them.

> Is there some better method to make technical features for my data?

This is the opposite approach, which is _additive_, requires being _familiar_ with different indicators and finding unique combinations and/or compositions of indicators to build strategies and signals. Unfortunately, there is _no_ shortcut to learning what kinds of indicators there are and what they attempt to filter or signal et al. So once you become more familiar with indicators and their output, this would be the optimal computational approach since dimensionality is reduced by your experience.

For me, TradingView has been a good sandbox to learn how indicators work and quickly prototype indicators since it provides a small feedback loop to work with. Not to mention, Pinescript is really easy to use. Of course there are other platforms and scripting languages to do the same.

Try different combinations of indicators or compositions and indicator parameters (lengths, periods, et al) to find entry/exit signals. It is very trial and error and some indicators are similar to each other potentially redundant if you normal/standardize them. Issue https://github.com/twopirllc/pandas-ta/issues/406 is an example of a standard RSI crossing strategy. Pandas TA also has two helper methods [tsignals](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/trend/tsignals.py) to generate Entries and Exits based on a Trend condition [AIExample Notebook](https://github.com/twopirllc/pandas-ta/blob/main/examples/AIExample.ipynb) and [xsignals](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/trend/xsignals.py) to generate Entries and Exits based on a Crossing Condition (#406 above).

Overall, be creative. Backtest **and** Forward Test your ideas.

Hope this helps! 🍀 
KJ

**Comment by twopirllc** [comment]
Hello @Stoner-sen,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
