### ISSUE TITLE
Multiple runtime warning errors

### ISSUE THREAD

**Issue by Pl0414141** [twopirllc/pandas-ta#441]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
TA-Lib                 0.4.21

**Describe the bug**
Adding all indicators shows the following warning errors:
```sh
/usr/local/lib/python3.8/dist-packages/pandas_ta/overlap/linreg.py:53: RuntimeWarning: invalid value encountered in double_scalars
  return rn / rd
/usr/local/lib/python3.8/dist-packages/pandas/core/arraylike.py:364: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
```

**To Reproduce**
Use a large dataset (>500MB) and apply all indicators as follows:
```python
    mi_estrategia = pandas_ta.Strategy(
        name="Data Strategy",
        description="Test.",
        ta=[
            {"kind": "sma", "length": 10},
            {"kind": "sma", "length": 20},
            {"kind": "sma", "length": 40},
            {"kind": "sma", "length": 60},
            {"kind": "sma", "length": 80},
            {"kind": "sma", "length": 100},
        ]
    )
    # Indcamos que indicadores queremos excluir. Normalmente estos vana ser los que hayamos puestos en la estrategia anterior.
    excluded_indicators = [
                        "sma",
                        "ad",
    ]

    # Aplicamos nuestros metodos.
    data.ta.strategy(mi_estrategia)

    # Aplicamos todos los indicadores posibles.
    data.ta.strategy(exclude=excluded_indicators)
```

**Expected behavior**
No warning errors

**Comment by twopirllc** [comment]
Hello @Pl0414141,

**Note:** These are only warnings and not necessarily a bug. You can [disable](https://www.google.com/search?q=python+disable+runtimewarning) warnings in your own code.

I _assume_ the ```data.ta.strategy()``` completes, correct? If so, have you checked that those indicators that are using ```ta.linreg()``` produce correct values?

> Adding all indicators shows the following warning errors:

Are those **all** the unique errors?

> Use a large dataset (>500MB) and apply all indicators as follows:

Please upload a subset of the CSV file with at least 250 ohlcv rows of the 500MB file that produces those _RuntimeWarnings_ so that I can replicate the Issue and debug it properly on my end.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@Pl0414141,

Reopen when you can narrow down and share relevant _ohlcv_ data so I can reproduce it.

Thanks,
KJ
