### ISSUE TITLE
Migration from ta.lib to pandas.lib

### ISSUE THREAD

**Issue by alexgreatparis** [twopirllc/pandas-ta#485]
Recently Successfully installed pandas-ta-0.3.14b0

But still now....
with
!pip install ta
import ta

I am currently using the following code (to make in final a SVR(kernel="rbf", epsilon=0.005))  : 

_**df_indicators = ta.add_all_ta_features(
    df, open="open", high="high", low="low", close="close", volume="volume", fillna=True).shift(1)**_

I would like to have the equivalent line code with pandas.ta to have in result the same df_indicators. Can you help me?

Thanks

**Comment by twopirllc** [comment]
Hello @alexgreatparis,

I won't be supporting _v0.3.14b0_ in the near future.

So, I recommend using the _development_ version which will be hopefully released soon. It has numerous bug fixes, better documentation and typing and performance improvements.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Second, I recommend you read _some_ of the README where already outlines what you are requesting. In particular, the section on [Programming Conventions](https://github.com/twopirllc/pandas-ta/tree/development#programming-conventions).

Here are the two Builtin Studies.
```python
import pandas_ta as ta

df = # your ohlcv data

# The Default Study: ta.AllStudy
# The following are equivalent:
df.ta.study()
df.ta.study("All")
df.ta.study(ta.AllStudy)

# CommonStudy
# df.ta.study(ta.CommonStudy)
```

Let me know if this works. 

Kind Regards,
KJ

**Comment by alexgreatparis** [comment]
Hello @twopirllc 
Thanks for your help, I'll look into it and test it.

**Comment by alexgreatparis** [comment]
Hi,
I run the install line you gave me and I have this error message

Collecting git+https://github.com/twopirllc/pandas-ta.git@development
  Cloning https://github.com/twopirllc/pandas-ta.git (to revision development) to c:\users\admin\appdata\local\temp\pip-req-build-s58imigv

  Error [WinError 2] Le fichier spécifié est introuvable while executing command git clone -q https://github.com/twopirllc/pandas-ta.git C:\Users\admin\AppData\Local\Temp\pip-req-build-s58imigv
Cannot find command 'git' - do you have 'git' installed and in your PATH?

Can you help me?

**Comment by twopirllc** [comment]
Hello @alexgreatparis,

You have two options.
1. Install [Git](https://git-scm.com/download/win)
    a. Install _development_ branch
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
2. Download _development_ branch **source** from [here](https://github.com/twopirllc/pandas-ta/tree/development)
    a. [How to download files from Github](https://www.itprotoday.com/development-techniques-and-management/how-do-i-download-files-github)
    b. Once **source** is saved in the directory of your app, you need to manually install it with pip.
        * [Installing packages with pip](https://packaging.python.org/en/latest/tutorials/installing-packages/)
        * [pip install from local dir](https://stackoverflow.com/questions/41535915/python-pip-install-from-local-dir/41537134)

I recommend installing Git, option 1. Hope this helps!

Kind Regards,
KJ

**Comment by alexgreatparis** [comment]
I'm really sorry to bother you with my installation problems. I did what you told me to do but I still have problems.
1/ I installed Git. I installed development branch without any problem. 
![image](https://user-images.githubusercontent.com/99539174/154506576-8b726325-0995-4458-afe8-fd785e3f54a5.png)

But after adding you pip install ... instruction I add this error message
![image](https://user-images.githubusercontent.com/99539174/154507088-e28a3ed6-215a-4c4b-a708-4dc66a54ab28.png)

So I tried the 2/ option
a. I did the dowload and I have the zip in my download directory
b. Once source is saved in the directory of your app -> I don't know where to save the zip content (ta was installed with anaconda so I have no idea of the installation process)
I really feel like the dumbest man alive but if you could continue to help me that would be nice.
Thanks in advance.

**Comment by alexgreatparis** [comment]
First of all thank you for spending time to support me in this installation. It's really nice.
I started doing what you asked me to do and here is the screenshot.
What do you think of it?
![image](https://user-images.githubusercontent.com/99539174/154798741-5fccbceb-92c3-4579-a83d-cc6faf5ec8ea.png)

**Comment by twopirllc** [comment]
Hello @alexgreatparis,

No problem. We all start somewhere.

It is saying Anaconda could not find ```virtualenv```. You need to install ```virtualenv``` with Anaconda first and then do the sequence of commands from my prior comment.

KJ

**Comment by alexgreatparis** [comment]
![image](https://user-images.githubusercontent.com/99539174/154971392-1858319b-523a-4ef2-90c4-7d6cf6e81ba6.png)
virtualenv seems ok, but it is source that is an issue.
What do you think?

**Comment by twopirllc** [comment]
@alexgreatparis,

Well, "/" are for unix like directories and "\" is for Windows directories. You seem to be using both and getting them mixed up.

Your last comment is using windows, so I believe it's:
```sh
PS .. > source env\bin\activate.bat
```

**Comment by twopirllc** [comment]
@alexgreatparis 

> for each line, you find the solution but I find it incredible that it is so complicated.

I hear you. Windows doesn't make it easy sometimes. 😒 

However, there is nothing stopping you from using Google Search to find solutions and try them out... just like me and everyone else that run into uncommon problems. If there is an error, someone has already likely posted the same question and there is similarly some sort of solution to try. For instance, you pip error [message](https://www.google.com/search?q=pip+there+was+a+problem+confirming+the+ssl+certificate) you received I would have to look up also.

However, based on your initial post, you got Pandas and "ta" and "pandas_ta" installed before. So how did you do that? You should be able to replicate the process since you did it already, correct?

Anyhow, lets forget the git and updated version of pandas_ta in a test directory that we tried for now. I just want to get you running. I will have an updated version of the library as soon as I can.

So go back to the directory or wherever you installed Pandas, pandas_ta (_v0.3.14b0_) and ta, assuming it's still there and give this a try:

```python
import pandas_ta as ta  # version v0.3.14b0

df = # your ohlcv data

# The Default Study: ta.AllStrategy
# The following are equivalent:
df.ta.strategy()
# df.ta.strategy("All")
# df.ta.strategy(ta.AllStrategy)

# CommonStudy
# df.ta.strategy(ta.CommonStrategy)
```

Let me know if you can run one of those.

<br/>

Lastly, I want to be clear that the issues you are having have **nothing** to do with Pandas TA.

KJ

**Comment by alexgreatparis** [comment]
![image](https://user-images.githubusercontent.com/99539174/155959299-b59b3a26-e667-499a-b8ca-f5c92d765f3d.png)
As you can see I took an exemple on youtube and put after it your code
- for df.ta.strategy() or df.ta.strategy("All") or df.ta.strategy(ta.AllStrategy) generate errors. I have attached the error txt file
- for df.ta.strategy(ta.CommonStrategy), no error
[strategy_errors.txt](https://github.com/twopirllc/pandas-ta/files/8152155/strategy_errors.txt)

**Comment by twopirllc** [comment]
Hello @alexgreatparis 

> As you can see I took an exemple on youtube and put after it your code

No it is impossible for me to tell it is from YT. Which YT video are you referencing?

> for df.ta.strategy() or df.ta.strategy("All") or df.ta.strategy(ta.AllStrategy) generate errors.

That is correct, they generate errors because these indicator groups/strategy/study include the **vwap** indicator which requires a DatetimeIndex as mentioned in the [Quick Start](https://github.com/twopirllc/pandas-ta#quick-start) section of the README (which includes how to create a DatetimeIndex). Whenever you need **vwap**, you need to create a DatetimeIndex.

> for df.ta.strategy(ta.CommonStrategy), no error

This is correct, no error, since ta.CommonStrategy does not have the **vwap** indicator in it's group/strategy/study.

<br/>

Since you chose ```ccxt``` for you example, then you need to do the following:


```python
from datetime import datetime
import pandas as pd
import ccxt, yfinance

import pandas_ta as ta

def to_datetime(t):
    return datetime.utcfromtimestamp(float(t) / 1000.0)

# Fetch Data
exchange = ccxt.binance()
ohlcv = exchange.fetch_ohlcv("ETH/USDT", timeframe="5m", limit=500)

# Prep DataFrame
df = pd.DataFrame(ohlcv, columns=["time", "open", "high", "low", "close", "volume"])
df["time"] = pd.to_datetime(df["time"].apply(to_datetime))
df.set_index("time", inplace=True)
print(df)

# Run Strategy
# df.ta.cores = 0  # Might get a speed increase if setting cores = 0.
df.ta.strategy(verbose=True)
print(df)

# Continue your Data Mining ...
```

<br/>

For other data providers, you will have to figure out how to set the DatetimeIndex.

Hope this helps! Good luck! 🍀 

KJ

**Comment by alexgreatparis** [comment]
Hi, do you someone who can help me to install the development version on my windows with a remote connection? I agree to pay for this.

**Comment by twopirllc** [comment]
Hey @alexgreatparis,

Unfortunately, I do not know of anyone. 🤷🏼‍♂️  Hopefully someone takes up your offer. If not, a new pip version will be coming out _soon_. 🤞🏼
