### ISSUE TITLE
Ray/Trendline/Linear Regression of two points

### ISSUE THREAD

**Issue by hadialaddin** [twopirllc/pandas-ta#503]
Say I have two points on the Dataframe (price and UNIX timestamp) and I want to draw a Ray (endless) that goes through these two points. Does Pandas TA or Pandas has a function for this? Is there an easy way to draw a Linear Regression ray, I just have the two points and I want to draw a Ray through them and get all the Datapoints (price and timestamp of each) say 1 week into the future to be predicted. Any example of how to use "linear_regression" ?

**Comment by doxg** [comment]
Hello, @hadialaddin. With a help of scikit-learn, I think it's possible to make simple function: 

```
from sklearn.linear_model import LinearRegression


def linear_regression(desired_period: list['start_date', 'end_date']):
    original_df = pd.read_csv('data.csv')
    
    X = original_df .iloc[:, 0].values.reshape(-1, 1) # Assuming first column contains UNIX timestamps
    X = X.astype(float) # Convert to nanoseconds since Jan 1, 1970.
    Y = original_df .iloc[:, 1].values.reshape(-1, 1) # Price column
    
    linear_regressor = LinearRegression()  
    linear_regressor.fit(X, Y)  # perform linear regression
    
    time_period = pd.date_range(start=desired_period[0], end=desired_period[1])
    new_x = time_period.values.astype(float).reshape(-1, 1)
    
    return linear_regressor.predict(new_x)
```

**Comment by twopirllc** [comment]
Hi @hadialaddin and @doxg,

Check out: ```help(ta.tos_stdevall)``` as developed in Issue #268. 
If you want a only the linear regression line for that indicator, set ```stds=[]```. And ```length``` is measured from the end of the DataFrame, otherwise it uses all the bars/rows. Currently, there is no early termination if you want to terminate before the last bar.

Also I have locally implemented a low level wrapper of ```sklearn```'s [```linear_regression```](https://github.com/twopirllc/pandas-ta/blob/720bbcf0196d363d621beeced8fba711990d075d/pandas_ta/utils/_math.py#L112) (if it's in your local environment) or by _default_ ```numpy```'s version. More info, see: ```help(ta.linear_regression)```. Though you will need to be explicit in how you want it to work.

Hope this helps!
KJ

**Comment by twopirllc** [comment]
Hello @hadialaddin,

I assume by no response that the solutions provided by @doxg and I were sufficient enough to achieve your goals. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
