### ISSUE TITLE
Trade Analysis

### ISSUE THREAD

**Issue by whatayush** [twopirllc/pandas-ta#524]
I apologize if this is a dumb question, but as I am not a professional coder some parts are still difficult to understand. With that, how can I use the performance part of the library?

For e.g I have 400 stocks, each one generates a buying date, buying price, selling date and selling price.  Sort of like this but for each stock.
![image](https://user-images.githubusercontent.com/104263942/165331673-75b81e4b-d4cd-4e27-99be-9eabd08cc184.png)
I then create a new database where I add up various metrics for each stock . 
![image](https://user-images.githubusercontent.com/104263942/165331775-d7c4a61c-f43f-4ac5-93c4-31394dc50eb2.png)

Is there a way to integrate pandas_ta to get more information out of my trading days? Like drawdown etc. If so how can I add it into my code? Any examples? 

Possible to utilize it for each stock out of 400 on loop? Or can it only work with individual stock and data?

Thanks

**Comment by twopirllc** [comment]
@whatayush,

> With that, how can I use the performance part of the library?

At this point, I wouldn't. It's BETA and currently stalled due to the overwhelming Bugs and Feature requests.

> Is there a way to integrate pandas_ta to get more information out of my trading days? Like drawdown etc. If so how can I add it into my code? Any examples?

Yes. You should use a Backtesting package such as [VectorBT](https://vectorbt.dev/) or [BackTrader](https://www.backtrader.com/). Those are the two I hear that most widely used and Pandas TA indicators
can be used with both of them.

If you have a Trade Log of actual trades from you broker, like your MMTC example above. I recommend looking for Trade Analyzer or write your own. Unfortunately, I do not know any off the top of my head. Though if you do come across on you find decent Trade Log Analyzer, please let us know!

Kind Regards,
KJ
