### ISSUE TITLE
Bollinger Bands is showing wrong data

### ISSUE THREAD

**Issue by Jnaneshnayak** [twopirllc/pandas-ta#537]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
0.3.14b0
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
Yes
```

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
No, this is the latest versions
```

**Describe the bug**
- Bollinger Bands is showing wrong data for 7 decimals.
- All BBL, BBM, BBU are all same value. 

**To Reproduce**
Applied Strategy:  **{"kind": "bbands", "length": 20, "col_names": ("BBL", "BBM", "BBU", "BBB", "BBP")}**
Refer [Using_Pandas_ta.png]

**Expected behavior**
Refer [screenshot: Using_Math.png]

**Screenshots**
<img width="334" alt="Using_Pandas_ta" src="https://user-images.githubusercontent.com/2044504/171472990-a9f184fb-6ce9-47ea-989a-adc7ed178c92.png">
<img width="473" alt="Using_Math" src="https://user-images.githubusercontent.com/2044504/171473591-1f85d427-93ef-4b4d-bcb4-6ebecda2b1b0.png">

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @Jnaneshnayak,

Since you stated you have **TA Lib** installed in your environment then the default calculation is ```talib.BBANDS()``` which not a bug in **Pandas TA**. This is a known precision Issue with TA Lib with more details discussed [here](https://github.com/mrjbq7/ta-lib/issues/157) and [here](https://github.com/mrjbq7/ta-lib/issues/151).

In short, there are two options (or a combination of both for your use case):
* Scale and Descale like #518
* Modify TA Lib source and rebuild for higher precision. (See links above)

Thanks for checking the precision of this library.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@Jnaneshnayak,

No worries.

> I will go with Scale /= Descale for now

Yeah, that's the quick fix.

> Source file update: https://github.com/mrjbq7/ta-lib/issues/190#issuecomment-374191246 

Yeah, it seems difficult but not really. Just a little manual work then the majority of precision issues are taken care of.

> Hope you fix the C code for us one day! 

Not touching that! 🤣  Have other things I want to build someday.

> Amazing work you have put in here. 👍🏼

Thank you!
KJ
