### ISSUE TITLE
psar() parameters

### ISSUE THREAD

**Issue by keith5551** [twopirllc/pandas-ta#538]
Apologies for this very basic question.  I'm developing an FX trading system, and learning to use Python + Pandas-TA along the way.

With this statement:

`psardf = ta.psar(high=psar_df["high"], low=psar_df["low"], close=psar_df["close"], start=0.01, step=0.01, max_step=0.2, fillna=True)`

I've used 'start', 'step', 'max_step' parameters to initialise the psar().  Is this correct? 

I've run it, and it seems to work without error, but the only documentation I can find is reference to parameters ap0, ap, max_ap.

Cheers.

**Comment by twopirllc** [comment]
Hello @keith5551,

First if you are not using the _development_ version, you should. (Better performance, documentation, et al...)

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Second, for help on an indicator:
```python
import pandas_ta as ta
help(ta.psar)
```

> I've run it, and it seems to work without error, but the only documentation I can find is reference to parameters ap0, ap, max_ap.

Those are the _correct_ parameters that ```help(ta.psar)``` describes. However _start, step and max_step_ have no effect; they are not valid _psar_ arguments in Pandas TA. Given your code above, I would replace _start_ with _af0_, _step_ with _af_, _max_step_ with _max_af_, 

Also the ```fillna``` argument fills the _na_ values with what you set it equal to. Given your code above, it will fill the _na_ values with ```True```. Not sure that is your intention since it's a non-numerical value. 🤷🏼‍♂️ See [Pandas fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html) for more info.

```python
import pandas_ta as ta

df = # your ohlcv data
psardf = df.ta.psar(af0=0.01, af=0.01, max_af=0.2)
```

Also here is an example of the resultant ```psardf``` (with default parameters):

<img width="1102" alt="Screen Shot 2022-06-03 at 9 46 04 AM" src="https://user-images.githubusercontent.com/18198392/171909515-662729d1-6956-4b13-be7d-1fea4c789c6d.png">

Note: The first 2 columns show long (green) and short (red) lines. If you need one line, you can combine them like so:
```python
# Combine Long and Short SAR"s into one SAR value
psar = psardf[psardf.columns[:2]].fillna(0)
psar = psar[psar.columns[0]] + psar[psar.columns[1]]
psar.iloc[0] = np.nan
```

The second chart keeps track of ```af```. The last chart shows when a reversal happens; psar changes from long to short or short to long. If you do not find those last two columns useful, just drop or exclude them.

Hope this helps!
KJ

**Comment by keith5551** [comment]
Thanks Kevin for your comprehensive response.  Very much appreciated.  This has helped me greatly.

Cheers. Keith
