### ISSUE TITLE
value errors on Chaikin Money Flow (cmf)

### ISSUE THREAD

**Issue by ISMAILHKYILDIZ** [twopirllc/pandas-ta#568]
this is stock independent, use any stock values generated by ta.cmf function are completely different from values in Tradingview CMF20.

**Comment by twopirllc** [comment]
Hello @ISMAILHKYILDIZ,

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ branch?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @ISMAILHKYILDIZ,

I assume by no response that _development_ branch resolved this issue. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
