### ISSUE TITLE
Possible KST & TRIX enhancements

### ISSUE THREAD

**Issue by fypdoctave** [twopirllc/pandas-ta#57]
Hi KJ,

Can you look into kst.py and maybe update the naming for kst_signal? Reason is that if I call KST multiple times (short, medium and long term parameters), KSTS_9 gets overridden. Its not a big deal to handle but wondering if this was intentional or not on your part. 
For example, following returns only one KSTS_9
df.ta.kst(append=True) #short-term
df.ta.kst(roc1=10, roc2=13, roc3=15, roc4=20, sma1=10, sma2=13, sma3=15, sma4=20, signal=9, append=True) #Medium term weekly
df.ta.kst(roc1=9, roc2=12, roc3=18, roc4=24, sma1=6, sma2=6, sma3=6, sma4=9, signal=9, append=True) #Long term monthly 

Another enhancement request is adding a signal logic to TRIX .py (similar to KST)? 

Thanks again for all of your work. This package is amazing!

**Comment by twopirllc** [comment]
Hello @fypdoctave,

Glad you like it!

Ok. So ```kst``` by itself is working as intended.  Because you are using the DataFrame accessor ```df.ta.kst(..., append=True)``` multiple times, the signal line is being overwritten by the last call (as you know).  Everything works as intended.

I do not know what version you are on, but @lluissalord made pull request #47 about a week ago with the ability at _prefixes_ and/or _suffixes_ to column names.  In your case, I would make a Strategy function to handle it for you.  For example:

```python
def kst3(df, **kwargs):
    append = kwargs.pop('kwargs', True)
    signal = kwargs.pop('signal', 9)
    pre_st = kwargs.pop('pre_st', 'short') # or suffix or whatever name you want here
    pre_mt = kwargs.pop('pre_mt', 'medium') # or suffix or whatever name you want here
    pre_lt = kwargs.pop('pre_lt', 'long') # or suffix or whatever name you want here

    df.ta.kst(signal=signal, prefix=pre_st, append=append) #short-term
    df.ta.kst(roc1=10, roc2=13, roc3=15, roc4=20, sma1=10, sma2=13, sma3=15, sma4=20, prefix=pre_mt, signal=signal, append=append) #Medium term weekly
    df.ta.kst(roc1=9, roc2=12, roc3=18, roc4=24, sma1=6, sma2=6, sma3=6, sma4=9, prefix=pre_lt, signal=signal, append=append) #Long term monthly

    return df

df = kst3(df)
```

As for ```trix```, I can add a signal line no problem.  Or you can make another function tailored to your needs.

```python
def trixy(df, **kwargs):
    append = kwargs.pop('kwargs', True)
    signal = kwargs.pop('signal', 9)
    ma = kwargs.pop('ma', 'sma')

    df.ta.trix(signal=signal, append=append)
    trix_name = df[df.columns[-1]].name
    df.ta(kind=ma, length=signal, prefix=trix_name, append=append)
    return df

df = trixy(df)
```

Thank you,
KJ

**Comment by fypdoctave** [comment]
Thanks for the quick response. I didn't know about prefix or suffix functionality so appreciate you pointing that out. Sounds great and very useful!
