### ISSUE TITLE
ta.macd not show result

### ISSUE THREAD

**Issue by jjlchui** [twopirllc/pandas-ta#570]
Hi, 
I am using 3.7.13 python without using TA lib in windows10.

I have used ta.macd for a while without any issue,  but suddenly an error msg pop-up. After upgrade to "pip install -U git+https://github.com/twopirllc/pandas-ta.git@development", there was not any data display. It displayed a while yesterday and disappeared again.... 

my coding: 
df.ta.macd(close=df['Close'], fast=12, slow=26, signal=9, append=True)

Please help or any advice. Thanks. 

joson

**Comment by twopirllc** [comment]
Hello @jjlchui,

Unfortunately, I can not help you without more information such as a screenshot or copy of the error as well as copy of the data that caused this error.

Kind Regards,
KJ

**Comment by jjlchui** [comment]
Hi KJ, 

Thanks for the reply. I don't know why it could not display the result yesterday. But it worked today. Anyway, I close this issue and will report to you if the issue comes up again!

Many thanks. 
joson

**Comment by jjlchui** [comment]
Hi, 

Need to bother you again. After one while the ta_MACD is gone, and the ta_RSI is gone too. Enclosed pls find the screen dump for you reference. It seems change the library 



![ta_macd](https://user-images.githubusercontent.com/41037036/183001010-8ae1c2f7-0e67-4d1a-b1bb-fd0bc9143779.png)

**Comment by twopirllc** [comment]
@jjlchui,

Thanks for sharing some code. However I do not see any errors in your screenshot nor have you provided sample data that replicates the error so it is still difficult to triage the Issue you claim.

Do note, that the _development_ indicators are highly restrictive about calculating an indicator if there is not likely to be any output of substance. In other words if you DataFrame does not meet the minimum length for the indicator, it will not calculate it and hence not append it to the existing DataFrame. For **macd**, see: https://github.com/twopirllc/pandas-ta/blob/6596651f33a6045b2f0e6c881288bd3aff01c175/pandas_ta/momentum/macd.py#L50-L59

Based on your (3,5) DataFrame, **macd** and **rsi** should never do any calculation because the don't meet the minimum length nor will they report any error.

KJ

**Comment by twopirllc** [comment]
Hello @jjlchui,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
