### ISSUE TITLE
Some of the candle pattern indicators are not able to find or compute results 

### ISSUE THREAD

**Issue by KrishnaRajule** [twopirllc/pandas-ta#571]
2crows | 3blackcrows | 3linestrike | 3starsinsouth | 3whitesoldiers | abandonedbaby | advanceblock | breakaway | concealbabyswall | counterattack | eveningdojistar | eveningstar | gapsidesidewhite | identical3crows | inneck | kicking | kickingbylength | ladderbottom | mathold | morningdojistar | morningstar | onneck | risefall3methods | separatinglines | stalledpattern | tristar | unique3river | upsidegap2crows | xsidegap3methods

The above stated candlestick patterns do not give any output/find patterns. I have also checked with different data and timestamp, but they still provide no output or are not able to find the respective patterns. I can also confirm for sure that some of them which do not find patterns for any data, these are as follows,

2crows | 3blackcrows | 3linestrike | 3whitesoldiers | abandonedbaby | counterattack | eveningdojistar | eveningstar | morningdojistar | morningstar | risefall3methods | separatinglines | stalledpattern | tristar | unique3river |

Please see if this issue occurs at your end and if yes, help me in finding the resolution for the same.

**Comment by twopirllc** [comment]
Hello @KrishnaRajule,

Please fill out:

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ branch? Did the upgrade resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
