### ISSUE TITLE
Description for Each Indicator

### ISSUE THREAD

**Issue by chandraveshchaudhari** [twopirllc/pandas-ta#584]
I am very new to technical indicators, and there are over 200 indicators. 

where can I find the documentation for each indicator with math? if documentation is not available, will this project accept my contribution?

**Comment by twopirllc** [comment]
Hello @chandraveshchaudhari,

There are a few ways listed under the Readme [Help](https://github.com/twopirllc/pandas-ta#help). Help with documentation is always welcome. 😎  

Documentation with math has been removed starting with the _development_ branch. Instead of including math in the help, links to the indicator source (which may or may not have math) have been provided. This helps keep documentation maintenance minimal.

What might be better instead, if your keen, is perhaps making a separate markdown file for the math of the indicators? What do you think?

Kind Regards,
KJ

**Comment by chandraveshchaudhari** [comment]
Hello KJ,

I will create markdown for indicators description and share it as soon as
possible.

Regards,

Chandravesh Chaudhari
Financial Artificial Intelligence Research,
CHRIST University (Bengaluru)

**Comment by twopirllc** [comment]
@chandraveshchaudhari,

So as not to reinvent the wheel completely, I highly recommend checking out the details provided by [Sierra Chart Indicators](https://search.sierrachart.com/?Query=indicator&submitted=true). A lot of them do have mathematical notation. Lastly no rush.

KJ

**Comment by chandraveshchaudhari** [comment]
Thanks, I'll check them out.

Regards,

Chandravesh Chaudhari
Financial Artificial Intelligence Research,
CHRIST University (Bengaluru)
