### ISSUE TITLE
Backtest/Signals Portfolio from Study

### ISSUE THREAD

**Issue by aress31** [twopirllc/pandas-ta#586]
Had a look at the `dev` version and it looks impressive! 🤩

I believe that it is not _yet_ possible to run backtests  - using `vectorbt` - by inputting a `Study` directly, i.e., configuring a set of parameters - and the of their interactions - to trigger buy/sell `signals`.

If I am wrong an example would be super!

EDIT: Additionally, I would like some information regarding `TS_Trends` and `TS_Trades` as I am not entirely sure what these values are made for.

Am I right in assuming that `TS_Trades` basically is a just a built-in counter to track trades and is controlled by the `trade_offset` param? What would `TS_Trends` then be? 🤔

Also, a stupid question, I am not really a financial analyst/trader so if the difference between a cross-signal and trend-signal could be made more explicit - and their different use cases -  that would be fantastic!

```python
def test():
    # requires 'yfinance' installed
    benchmarkdf = ta.df.ta.ticker("AAPL", timed=True)

    benchmark_trends = trends(
        benchmarkdf, {"mamode": "sma", "fast": 50, "slow": 200})

    benchmark_signals = benchmarkdf.ta.tsignals(
        benchmark_trends, asbool=True, trade_offset=1, append=True)

    # Buy signal 
    print(benchmark_signals[(benchmark_signals['TS_Entry'] == True)])

    # Sell signal 
    print(benchmark_signals[(benchmark_signals['TS_Exits'] == True)])
```
Also, let's say that I want to create a very simple signal where if `rsi > 70` then `vectorbt` should `sell` whereas if `rsi < 30` then `vectorbt` should buy.

Would it be better to use `trends` or `cross` and what the code would look like? Something like that?

```python
def trends(df: pd.DataFrame, length: int = 14, threshold: int = 70):
    return ta.rsi(df.Close, length) > treshold
````

Using this approach, how would `benchmarkdf.ta.tsignals` know which condition sets `TS_Entry` and which sets `TS_Exit`?

**Comment by twopirllc** [comment]
> I believe that it is not yet possible to run backtests - using vectorbt - by inputting a Study directly, i.e., configuring a set of parameters - and the of their interactions - to trigger buy/sell signals.

That is correct. Not directly. Perhaps at one point. 🤷🏼‍♂️ 

An example of using ```ta.tsignals()``` is [here](https://github.com/twopirllc/pandas-ta/blob/development/examples/TA_Analysis.ipynb) and explained each of the four columns with sample charts as well as ```help(ta.tsignals)```.

> Also, let's say that I want to create a very simple signal where if rsi > 70 then vectorbt should sell whereas if rsi < 30 then vectorbt should buy.

You would use cross signals, since it is _event_ based and not _state_ based like trend signals. An example of RSI Crossings is provided in ```help(ta.xsignals)```. You will need to fiddle with it yourself. It also helps to plot the signal results like in the [example notebook](https://github.com/twopirllc/pandas-ta/blob/development/examples/TA_Analysis.ipynb) to ensure you are on the right track.

> Using this approach, how would benchmarkdf.ta.tsignals know which condition sets TS_Entry and which sets TS_Exit?

Here is the core calculations for the 4 columns of ```ta.tsignals()```. Perhaps that will help? Otherwise, I am uncertain what you question is asking for. 🤷🏼‍♂️ 

https://github.com/twopirllc/pandas-ta/blob/084dbe1c4b76082f383fa3029270ea9ac35e4dc7/pandas_ta/trend/tsignals.py#L17-L21

KJ

**Comment by twopirllc** [comment]
Hello @aress31,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
