### ISSUE TITLE
How to use the KDJ indicator?

### ISSUE THREAD

**Issue by Qwertzi01** [twopirllc/pandas-ta#595]
Hello, I'm new to pandas/FreqTrade and want to use pandas-ta because this library provide the KDJ indicator.
But I'm really confused how to use the KDJ in my strategy - how I can measure if the KDJ is positive or negative? 
Thx in advance.

**Comment by twopirllc** [comment]
Hello @Qwertzi01,

> ... how I can measure if the KDJ is positive or negative?

Here is an example subchart of **kdj**. Seems many are mostly positive, however one or more lines may dip negative from time to time.

<img width="741" alt="Screen Shot 2022-09-24 at 9 28 44 AM" src="https://user-images.githubusercontent.com/18198392/192109079-4e86ecfd-c690-43ea-a05a-78ebf48694dd.png">

Testing if positive or negative is fairly straightforward if testing a constant (like 0).

<img width="207" alt="Screen Shot 2022-09-24 at 9 33 42 AM" src="https://user-images.githubusercontent.com/18198392/192109147-126f1a7d-dcef-4d8f-a938-d64a189bc561.png">
<img width="215" alt="Screen Shot 2022-09-24 at 9 33 26 AM" src="https://user-images.githubusercontent.com/18198392/192109153-0648c835-8d33-4ba2-95a6-07e224bca675.png">

Additionally, please read this [section](https://github.com/twopirllc/pandas-ta#programming-conventions) on typical ways to use Pandas TA.

<br/>

Finally for my future reference, please fill out the following:

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.


Kind Regards,
KJ

**Comment by Qwertzi01** [comment]
Thx for the fast answer, but I think I didn't ask the question clearly. 
I'm interested in getting **buy and sell signals** from the KDJ as shown in the example below:

![kdj_example](https://user-images.githubusercontent.com/7136516/192134723-4dfcf441-63bd-4d2d-8259-8dc292188fa6.jpg)

With my example above a clear sell signal is given if the J-line cross from top to bottom K- and D-line,
a clear buy signal will happen if the J-line cross from bottom to top the K- and D-line (blue marked).

**Comment by twopirllc** [comment]
@Qwertzi01,

Please install the _development_ version if you have not already. Here is the [README](https://github.com/twopirllc/pandas-ta/tree/development).

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Based on your sample, it looks like the all three lines cross at the same point.
1. J crossing K or J crossing D is the same. The question is, which is preferable?
2. Or does J absolutely need to cross both K and D lines? If so, that is a bit more to setup.

For the sake of simplicity, I will assume (1.) with J crossing D.
<img width="750" alt="Screen Shot 2022-09-28 at 8 21 14 AM" src="https://user-images.githubusercontent.com/18198392/192819248-ff9f5295-b75f-4c82-a8f2-f1e94b5cd796.png">

<br/>

**Note**  ```ta.tsignals()``` returns 4 columns, I only showed the first two: Trends and Trades. The last two columns are the signal Entries and Exits which you can plot for verification.

Hope this helps
KJ

**Comment by Qwertzi01** [comment]
> 1. J crossing K or J crossing D is the same. The question is, which is preferable?

Yes, point 1. is correct, preferable how in your example -> if J is crossing K or D is not so important.
But I'm struggling to implement it in a FreqTrade strategy:

```
import pandas_ta as pdta
pdta_kdj = pdta.kdj(dataframe)
kline, dline, jline = pdta_kdj.iloc[:,0], pdta_kdj.iloc[:,1], pdta_kdj.iloc[:,2]
```

Is my above example the right way to use it without Pandas TA DataFrame Extension?

**Comment by twopirllc** [comment]
@Qwertzi01

No that is not the correct way to calculate an indicator _without_ the DataFrame Extension Convention. What you want is the [_Standard_](https://github.com/twopirllc/pandas-ta/tree/development#standard) Convention.

If you are having FreqTrade Issues, please post an Issue on their repo.

KJ

**Comment by Qwertzi01** [comment]
I figured it out how to implement the KDJ indicator into a [FreqTrade](https://github.com/freqtrade/freqtrade) strategy with the [_Standard_](https://github.com/twopirllc/pandas-ta/tree/development#standard) Convention.
For all who are maybe interested (it's similar also applicable to other pandas-ta related indicators):

```
import pandas_ta as pdta

pdta_kdj = pdta.kdj(dataframe['high'], dataframe['low'], dataframe['close'], length=9, signal=3)
dataframe['kdj_k'] = pdta_kdj.iloc[:,0]
dataframe['kdj_d'] = pdta_kdj.iloc[:,1]
dataframe['kdj_j'] = pdta_kdj.iloc[:,2]

long = dataframe['kdj_j'] > dataframe['kdj_d']
short = dataframe['kdj_j'] < dataframe['kdj_d']
```
