### ISSUE TITLE
Parallel Calculation of Indicators

### ISSUE THREAD

**Issue by athenawisdoms** [twopirllc/pandas-ta#62]
Hi, thanks for the amazing library!

Is there a way to perform parallel processing of the technical indicators, especially if you are trying to calculate all of them, such as 

```
df.ta.strategy(name='all')
```

**Comment by twopirllc** [comment]
Hello @athenawisdoms,

Thanks! 
Should be doable. I'll look into it.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @athenawisdoms ,

You are in luck!  After brushing up on Python's implementation of multiprocessing and multithreading, I was able to get some performance out of it. It took a bit longer than expected since the solution was the inverse of many basic tutorials. However, I finally found one solution online that was similar that helped piece it together.

Anyhow I will update ```pandas-ta``` in the next day or so. By default, multiprocessing is **not** enabled, so you will have to enable it before running ```strategy()```.
```python
# Enable multiprocessing
df.ta.mp = True
dt.ta.strategy()

# You can time the run as well and verbose output
df.ta.strategy(timed=True, verbose=True)

# You can even change the number of multiprocessing cores to use
# There is some internal optimizing of cores to attempt to maximize performance.
df.ta.strategy(timed=True, verbose=True, cores=8)
```

Thanks,
KJ
