### ISSUE TITLE
bbands bug which equateс PERCENT to BANDWIDTH when offset is set to >0

### ISSUE THREAD

**Issue by dnentchev** [twopirllc/pandas-ta#637]
row 45 in the code is ```percent = bandwidth.shift(offset)``` and it should be ```percent = percent.shift(offset)```

**Comment by twopirllc** [comment]
Hello @dnentchev,

Since you have shared nothing about what you are using, I assume it is the _main_ branch _v0.3.14b_ which had that bug. However that bug does not exist on the _development_ branch. Next time you have an Issue, **please** fill out the bug report with the requested questions.

Kind Regards,
KJ
