### ISSUE TITLE
SMA with length of 1 is not working

### ISSUE THREAD

**Issue by SpartanzRaj** [twopirllc/pandas-ta#647]
Hi, 
I tried sma and ema with length 1. I received the following error response.

```python
df['sma34'] = df.ta.ema(close='Close',length=1)
```
```sh
Library/Python/3.9/lib/python/site-packages/pandas_ta/core.py", line 1159, in ema
  File "talib/_func.pxi", line 2936, in talib._ta_lib.EMA
  File "talib/_common.pxi", line 47, in talib._ta_lib._ta_check_success
Exception: TA_EMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)
```

I know sma with length 1 is not going to do anything. But Some other indicator using sma as base. When pass 1 to **stochastic** , it doesn't execute, because of sma failure

**Comment by twopirllc** [comment]
Hello @SpartanzRaj,

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
