### ISSUE TITLE
ValueError with 4-hour data, but not 1-hour data 

### ISSUE THREAD

**Issue by toncorp** [twopirllc/pandas-ta#650]
Using most up to date versions of everything. As title states, I'm getting a ValueError when I run my code with 4-hour data, but not with 1-hour data. I'm using CSVs. 1-hour data runs perfectly as expected. However, when I export data in exactly the same way, just changing the time interval to 4-hour, I get this warning: "FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version" which I don't get when I run the code with the 1-hour data, and then I get this error: "ValueError: cannot reindex on an axis with duplicate labels". The error is originating with df.ta.macd(append=True), however when I comment it out, it just throws the same error with a new line, in my case df.ta.msi(append=True).

Any ideas what's causing the error to occur with 4-hour data, but not 1-hour?

**Comment by twopirllc** [comment]
Hello @toncorp,

Please provide more detail. Thanks! 😎 

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
