### ISSUE TITLE
don't equal stochastic

### ISSUE THREAD

**Issue by 190706036** [twopirllc/pandas-ta#651]
Don't equal stoch from mt5  and tradingview. Why ? 

![image](https://user-images.githubusercontent.com/108771246/216932897-3a9e9263-3155-4a09-9ce3-c4c00ab6f2db.png)
it is my stoch function but don't equal mt5 stochastic.

![image](https://user-images.githubusercontent.com/108771246/216933349-428f9b97-d2e8-4936-bebb-3753f51a4e92.png)

![image](https://user-images.githubusercontent.com/108771246/216934465-ea44cf20-e764-48dc-8075-a33493d27341.png)

![image](https://user-images.githubusercontent.com/108771246/216934605-8f9f8fde-98fc-49c5-ae21-d7b089131fd5.png)

**Comment by twopirllc** [comment]
Hello @190706036,

Still missing some useful information!

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by twopirllc** [comment]
@190706036,

> Why?

Why indeed?

Note: This library tries to be accurate with TA Lib **first** and TV **second** (if possible). Otherwise that's the most accurate numerical calculation at the time.

<img width="725" alt="Screenshot 2023-02-09 at 10 02 08 AM" src="https://user-images.githubusercontent.com/18198392/217905464-d431ff74-c46c-4e45-b738-6d7f406bc019.png">

Unfortunately brokerages and trading platforms (like mt4/5, ToS, IBKR, et al) that do not allow the export of raw _tohlcv_ **and** it's associated indicator data makes indicator testing nearly equivalent to a Block Box. 😑

But contributions are welcome! 😎 I do not think you are alone for some mt4/5 calculations.
