### ISSUE TITLE
[Question] How to incrementally calculate indicators

### ISSUE THREAD

**Issue by pinkfrog9** [twopirllc/pandas-ta#723]
In the live trading setting instead of backtesting one, how can I incrementally calculate the indicators whenever I receive new rows of data?

**Comment by twopirllc** [comment]
Hello @pinkfrog9,

You will need to install the _development_ version since it has fixes and updates across the board as well as handling incremental calculations.

Here is the _incremental_ test code demonstrated in [tests/test_studies.py](https://github.com/twopirllc/pandas-ta/blob/development/tests/test_studies.py)

```python
@pytest.mark.parametrize("talib", [False, True])
def test_study_all_incremental_rows(df, all_study, talib):
    MAX_ROWS = 90
    df = df.iloc[:MAX_ROWS]   # Trim for this test

    for i in range(0, MAX_ROWS):
        _df = df.iloc[:i]
        _df.ta.study(all_study, cores=0, talib=talib)
        # Break when max columns reached
        if _df.shape[1] - df.shape[1] == ALL_COLUMNS:
            assert _df.shape[1] > df.shape[1]
            break
```

Essentially put your indicators in a _Study_, then when the DataFrame receives a new row(s) call _df.ta.study(your_study, cores=0, **kwargs)_ to update the DataFrame with the new calculations.

Kind Regards,
KJ

**Comment by pinkfrog9** [comment]
Thanks for the detailed reply.
