### ISSUE TITLE
Issue with kwargs for Stoch TA

### ISSUE THREAD

**Issue by nedlecomber** [twopirllc/pandas-ta#726]
Hi there, 
I believe there's an error in the kwargs on line 1107 of core.py (Stoch function).
I was having issues changing the k, k smooth and d paramenters, using new args wouldn't change the TA paramenters. 

Line 1107 original core.py file:
```python
result = stoch(high=high, low=low, close=close, fast_k=fast_k, slow_k=slow_k, slow_d=slow_d, mamode=mamode, offset=offset, **kwargs)
```
I changed it to:
```python
result = stoch(high=high, low=low, close=close, k=fast_k, smooth_k=slow_k, d=slow_d, mamode=mamode, offset=offset, **kwargs)
```
This fixed the issue, for me. 
Thanks!

**Comment by luisbarrancos** [comment]
I think that's fixed in development.

In the *master* branch you can see that [core.py:1103](https://github.com/twopirllc/pandas-ta/blob/084dbe1c4b76082f383fa3029270ea9ac35e4dc7/pandas_ta/core.py#L1103) is using the ```fast_k=None, slow_k=None, slow_d=None``` keyword arguments, which don't exist in the indicator in [momentum/stoch,py:7](https://github.com/twopirllc/pandas-ta/blob/084dbe1c4b76082f383fa3029270ea9ac35e4dc7/pandas_ta/momentum/stoch.py#L7), which has keyword arguments ``` k=None, d=None, smooth_k=None```.
In the *development* branch, you can see that [core.py:1093](https://github.com/twopirllc/pandas-ta/blob/aaffdbe7c36b85cc114eb01041c15db4c214935c/pandas_ta/core.py#L1093) already has the keyword arguments ```k=None, d=None, smooth_k=None``` matching the indicator call in [momentum/stock.py:17](https://github.com/twopirllc/pandas-ta/blob/aaffdbe7c36b85cc114eb01041c15db4c214935c/pandas_ta/momentum/stoch.py#L17), namely ```k=None, d=None, smooth_k=None```.

**Comment by twopirllc** [comment]
Hello @nedlecomber,

Thanks for noticing and recommending a solution to the _main_ branch for _stoch_ core.py. However, this issue has been fixed as noted by @luisbarrancos.

I recommend using the _development_ branch for the time being and let us know of any issues regarding that branch. 😎 

Kind Regards,
KJ

**Comment by nedlecomber** [comment]
Apologies guys, didn't realise I was using the wrong branch. Thanks for the swift reply! :)
