### ISSUE TITLE
KVO Vs TradingView KVO

### ISSUE THREAD

**Issue by RaimondodelBalzo** [twopirllc/pandas-ta#734]
Hello there,
Thanks a lot for your project and all the features of this library. I use it every day!
I am currently using many of the momentum and volume indicators without problems.
Only one "fails" compared to TradingView: KVO
I am sure that it has to do with some parameters or some average applied when I recall the function.

Could please let me know the parameters to have the same results of TradingView?

Thanks.

Best,
Raimondo

**Comment by Groni3000** [comment]
I took most used TradingView KVO indicator by HPotter. Here is his code:
```
study(title="Klinger Volume Oscillator (KVO)", shorttitle="KVO")
TrigLen = input(13, minval=1)
FastX = input(34, minval=1)
SlowX = input(55, minval=1)
xTrend = iff(hlc3 > hlc3[1], volume * 100, -volume * 100) // <--- Here is what can cause the problem for you
xFast = ema(xTrend, FastX)
xSlow = ema(xTrend, SlowX)
xKVO = xFast - xSlow
xTrigger = ema(xKVO, TrigLen)
plot(xKVO, color=blue, title="KVO")
plot(xTrigger, color=red, title="Trigger")
```

So the only thing you need to do is simply multiplying volume by 100:
```python
import pandas_ta as pdt

pdt.kvo(h, l, c, 100 * v)
```
Still, you may not have the same result, because of different data sources. For example, I downloaded QQQ from yfinance and volumes was slightly "not the same". But, as I can see, pandas_ta makes the same logic as TradingView by default, like `ewm` with `span` and first value calculated as simple mean...

**Comment by RaimondodelBalzo** [comment]
Thanks for your reply and help. And sorry for getting back to you after a couple of days.

<img width="1824" alt="Screenshot TradingView" src="https://github.com/twopirllc/pandas-ta/assets/48590658/42fd2143-411c-48ed-aca0-bdb141aac738">
[Input.csv](https://github.com/twopirllc/pandas-ta/files/13305705/Input.csv)
[Output.csv](https://github.com/twopirllc/pandas-ta/files/13305706/Output.csv)

I have attached a small dataset (one stock) and I applied this command:
data2.ta.kvo(high=data2["high"], low=data2["low"], close=data2['close'], volume=data2["volume"]*100, append=True)

The two results are different. What I am missing?
Thanks again.

**Comment by Groni3000** [comment]
@RaimondodelBalzo Sorry for my late appearance too)
As I told, different sources, I guess.
For example, first row (07-07-2023) in Input.csv:
`volume = 63600`
And in TradingView `volume = 63639`, you can see it in this screen:
![image](https://github.com/twopirllc/pandas-ta/assets/72792408/bfca8760-9c88-49bc-9a67-353e334fa38f)

The difference is small, but in `ewm` next value depends on previous and this indicator calculates several such `ewm`s. 
Can you clarify your data source? If you got it from TradingView - it is strange because I even plot volume and it says 63639...
![image](https://github.com/twopirllc/pandas-ta/assets/72792408/d5b3fd96-f107-49e1-9f0b-2320ad8a6587)

If you manage to download exactly TradingView data and test it - that would be perfect, but as I know, it is not free [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]

Or, maybe, I didn't understand you and Input.csv is TradingView source, but that would be strange, because TV calculations takes volume that I plot.

**Comment by Groni3000** [comment]
@RaimondodelBalzo, sorry for my misleading and bad answer =( Here is an update

pandas_ta version of `signed_series` in `kvo` uses hardcoded initial (first) value of 1.
tradingview version uses -1.
So you will never have the same output.
You can see it here:
**---------------pandas_ta---------------**: 
![image](https://github.com/twopirllc/pandas-ta/assets/72792408/498c6296-23d6-4d25-8139-594975e36b2d)

**---------------tradingview---------------**:
![image](https://github.com/twopirllc/pandas-ta/assets/72792408/f2957951-d5ae-493a-98f1-7ec207be186f)

Other things should be exactly the same. 

AND!!!! Very important!!!
This indicator is REALLY sensative! You won't get the same values even if you exclude only one first point. Here is example for your Input.csv:
![image](https://github.com/twopirllc/pandas-ta/assets/72792408/ff7fdfed-2f46-4d2c-a5b6-5cd746129081)

So, if you use only part of your data - there is no reason to expect the same output as tradingview indicator. Moreover, sadly to say, you will not have the same output even if you use entire quotes from tradingview (I mean with correct volumes) cuz it has different sign for the first value in `sv`.

**Comment by RaimondodelBalzo** [comment]
@Groni3000  Thanks for the followup. It would be enough to have an almost-similar value. With the signal following the same logic. But it is really hard to see if this is true. So what I gather is that it would be better to do my own KVO calculation in python without using this package. Am I correct?

**Comment by Groni3000** [comment]
@RaimondodelBalzo Well, this is, maybe, is the best option. It's not that hard to implement, I guess. It's hard to check correctness. I had to waste ~15 mins to write all volume values by hand to compare computation results xDD Programmer ahahhaha. Here is my funcs as inspiration to you if you need them:

```python
def my_typ_price(h, l, c):
    return (h + l + c) / 3

def my_signed_series(s, init=-1):
    # init = -1 for TradingView
    # init = 1 for pandas_ta
    res = s.diff(1)
    res[res > 0] = 1
    res[res < 0] = -1
    res.iloc[0] = init
    return res

def my_ewm(ser:pd.Series, window:int):
    # Here I didn't investigate how TradingView ewm behaives with np.NaN values,
    # perhaps they make something like this:
    #
    # nan_vals_idx = np.where(ser.isna())[0]
    # first_non_nan_idx = 0 if nan_vals_idx.size == 0 else nan_vals_idx[-1] + 1      #<--- That's not exactly correct, they implement it differently (if prev value is NaN ===> simple moving avarage or something like this), but with correct series (only first N values COULD be NaNs) it should be fine 
    # nth = ser.iloc[first_non_nan_idx:first_non_nan_idx+window].mean()
    # ser = ser.copy()
    # ser.iloc[:first_non_nan_idx + window] = np.NaN
    # ser.iloc[:first_non_nan_idx + window - 1] = nth
    #
    # I checked it with only non NaN values and this ewm is exactly the same as TradingVeiw version
    
    ser = ser.copy()
    nth = ser.iloc[:window].mean() 
    ser.iloc[:window] = np.NaN
    ser.iloc[window-1] = nth
    
    return ser.ewm(span=window, adjust=False).mean()

def my_kvo(h, l, c, v, w_1=34, w_2=55, w_3=13):
    tp = my_typ_price(h, l, c)
    sv = v * my_signed_series(tp)
    kvo = my_ewm(sv, w_1) - my_ewm(sv, w_2)
    kvo_signal = my_ewm(kvo, w_3)
    
    return kvo, kvo_signal
```

**Comment by twopirllc** [comment]
Hello @RaimondodelBalzo & @Groni3000 

Thanks for using Pandas TA!

Apologies for the slow reply and hashing out the details in the mean time with good analysis and solutions. It helps make reviewing indicators easier. 😎 

I don't remember exactly if the ```1``` in ```signed_volume = volume * signed_series(hlc3(high, low, close), 1)``` was by design or just a mistake. 🤦🏼‍♂️ 

TradingView also has **Klinger Oscillator**:
 ```c
//@version=5
indicator(title="Klinger Oscillator", format=format.volume, timeframe="", timeframe_gaps=true)
var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")
sv = ta.change(hlc3) >= 0 ? volume : -volume
kvo = ta.ema(sv, 34) - ta.ema(sv, 55)
sig = ta.ema(kvo, 13)
```

But if I only need to replace the initial ```signed_volume()``` to ```-1```, then even better if that is the consensus. 😎 

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @RaimondodelBalzo & @Groni3000 

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
