### ISSUE TITLE
Simple bug on downloading data using example Backtesting with vectorbt

### ISSUE THREAD

**Issue by MrBolt177** [twopirllc/pandas-ta#752]
Just tried to go step by step with the example [https://github.com/twopirllc/pandas-ta/blob/main/examples/VectorBT_Backtest_with_Pandas_TA.ipynb](url)

It didn't work, received and error: UnboundLocalError: local variable 'df' referenced before assignment

**Comment by twopirllc** [comment]
Let's get started with some more information please.

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

Thanks

**Comment by Mahesha-kale** [comment]
The bug is due to the following line where it is checking if the data frame is empty or None in core.py or it might be a different issue completely.  This issue is occurring as even after checking the df is None you are still checking df.shape inside the print statement which is giving an issue as None object don't have any shape attribute.
![bugissue](https://github.com/twopirllc/pandas-ta/assets/76392142/7ca8aa54-ea7a-48d8-a769-72b166cc5c29)

**Comment by twopirllc** [comment]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have **yfinance** installed? Did it resolve the issue?**


**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Have you tried the _development_ version of the notebook after updating to the _development_ branch?**
[VectorBT Backtest Notebook](https://github.com/twopirllc/pandas-ta/blob/development/examples/VectorBT_Backtest_with_Pandas_TA.ipynb)

**Comment by twopirllc** [comment]
@MrBolt177 @Mahesha-kale 

After going through some ```yfinance``` issues, have you tried?
```sh
$ pip install yfinance==0.1.62
```
