### ISSUE TITLE
NATR in non TA-lib mode

### ISSUE THREAD

**Issue by shubhamsatyarth** [twopirllc/pandas-ta#755]
```python
# Calculate Result
    if Imports["talib"] and mode_tal:
        from talib import NATR
        natr = NATR(high, low, close, length)
    else:
        natr = scalar / close
        natr *= atr(high=high, low=low, close=close, length=length, mamode=mamode, drift=drift, offset=offset, **kwargs)
```

I guess when talib is false, even then atr is calculated in talib mode since talib is False is not passed in atr call.

**Comment by twopirllc** [comment]
Hello @shubhamsatyarth,

Please provide some more information. Thanks! 😎 

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
