### ISSUE TITLE
Adjusted Close vs Close

### ISSUE THREAD

**Issue by Winch17** [twopirllc/pandas-ta#757]
Hi,

I would like to test the impact of changing the Pandas.ta stock output being "Adjusted Close" vs "Close".  Can you tell me where I can change the config.sys pandas_ta file to default at "Close" price instead of "Adjusted Close"?

Thank you in advance!

**Comment by twopirllc** [comment]
Hello @Winch17,

Could you please provide a bit more information to make it easier to assist? By the way, Pandas TA does not have a configuration file and by default uses the "Close" column. The [README](https://github.com/twopirllc/pandas-ta#dataframe-properties) DataFrame properties section describes how to enable and disable an adjusted close column.

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide sample code.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by Winch17** [comment]
Hi,

Thank you for your quick reply.

I am using the recent pandas-ta version 0.3.14b0, newly installed 2 weeks ago.  I do not have TA Lib installed... spent a day to install it without success.

This is not an issue, I believe Pandas-ta delivers the adjusted close price by default (df.ta.ticker function) which is in line with expectations.   I just want to test the close price, not the adjusted price to compare results adjusted close vs close.  

I proceeded using yf.ticker the Yahoo Finances function to obtain the close price but would have prefer to do it through Pandas-ta. Pandas-ta does not give me that flexibility unless I am able to modify the config file which not sure how to proceed.

Thank you.


Vincent

**Comment by twopirllc** [comment]
Hello @Winch17 

Pandas TA wraps the [yfinance](https://github.com/ranaroussi/yfinance) package, so those are the parameters you need to include/modify. You can find all _yfinance.history()_ options [here](https://github.com/ranaroussi/yfinance/blob/main/yfinance/base.py). With Pandas TA, one can do:

```python
df = df.ta.ticker("aa", auto_adjust=False)
```

Also Pandas TA v _0.3.14b0_ is the last released version on [pypi](https://pypi.org/). The most recent version is the _development_ one which has many more improvements.

Hope this helps!
KJ

**Comment by Winch17** [comment]
Thank you Kevin , this works perfectly!
