### ISSUE TITLE
Discripency Between Yahoo Finance and Panda's TA in Accumulation/Distribution Indicator

### ISSUE THREAD

**Issue by ibrahimmina** [twopirllc/pandas-ta#783]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0
**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
pandas-ta                 0.3.14b0
**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
No
**Describe the bug**

I am trying to calculate Accumulation/Distribution Indicator using Pandas TA

I have compared the output with Yahoo Finance and it seems that the numbers are mismatching

Below is a sample for MSFT Day Interval from both Panda's TA and Yahoo Finance

![image](https://github.com/twopirllc/pandas-ta/assets/71660135/3ed69b45-89fd-4608-8843-b3ce3e37a986)

<img width="1021" alt="image" src="https://github.com/twopirllc/pandas-ta/assets/71660135/7cf59b41-9956-42fa-88e4-98fc9b4aacea">

While the graphs are relevant the numbers in Yahoo Finance are in terms of Billions While from Panda's TA are in terms of Millions

**To Reproduce**
Provide sample code.
```python
aggs = []
for a in polygon_client.list_aggs(ticker="MSFT", multiplier=1, timespan="day", from_="2023-12-04", to="2024-04-05", limit=50000):
    aggs.append(a)
stock=pd.DataFrame(aggs)
stock.ta.ad(high=stock['high'], low=stock['low'], close=stock['close'],volume=stock['volume'], open_=stock['Open'])
```

**Expected behavior**

Below is pandas ta output 
```sh
0     1.937360e+05
1     1.893756e+07
2     2.617762e+06
3     1.486887e+07
4     3.113148e+07
          ...     
80    1.862813e+08
81    1.915287e+08
82    1.943746e+08
83    1.819667e+08
84    1.819712e+08
Name: ADo, Length: 85, dtype: float64
```

last item is 181 Million while yahoo Finance shows 1.62 Billion

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @ibrahimmina,

Pandas TA is focused primarily on TA Lib which is the _de facto_ library of indicators and testing indicators against it is relatively easy. TradingView (TV) is _secondary_ and is ubiquitous. Running tests these tests are easy and fast to do.

On the other hand, all the other trading and financial data platforms like _Think or Swim_, _Trade Station_, _Yahoo Finance_, et al are black boxed systems where the exportation of both _ohlcv_ and indicator values range from cumbersome to impossible. Without easily exportable data, comparing hundreds of indicator values via charts from these platforms is not only extremely slow to manually do but also error prone. Thus these platforms will not be covered on a free basis. However Pandas TA is open source so you or anyone else are welcome to modify or extend the functionality however they want and submit a pull request if they would like it included.

> I have compared the output with Yahoo Finance and it seems that the numbers are mismatching

You passed all of _ohlcv_ into **ad**.
```python
stock.ta.ad(high=stock['high'], low=stock['low'], close=stock['close'],volume=stock['volume'], open_=stock['Open'])
```

However **ad** is one of the few indicators where one or more Series is option-able. In particular, **ad** does not require the _open_ for it's calculation . So it is possible that Yahoo Finance also does not include _open_ values in their calculation, only _hlcv_. But I don't know for sure. 🤷🏼‍♂️ So you could try excluding _open_ like so:

```python
stock.ta.ad(high=stock['high'], low=stock['low'], close=stock['close'], volume=stock['volume'])
```

Since you are calling **ad** from the DataFrame Extension _.ta.ad()_, you can simplify your code as follows:

```python
stock.ta.ad()
# or 
stock.ta.ad(append=True)  # if you want/need to append the results to the stock DataFrame
```

Additionally, I noticed that you are pulling data from Polygon which may or may not be an exact copy of Yahoo Finance data. If they are different, then you are comparing _apples_ with _oranges_ which is common mistake. 

Finally, it is good practice to read the indicator documentation, ```help(ta.ad)```, and/or view the [source code](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/volume/ad.py) **and try** all possible variations if the default parameters do not return as expected _before_ submitting a Bug issue.

Kind Regards,
KJ
