### ISSUE TITLE
Return a Series of NaNs, with a name, rather than just a None when an indicator cannot be calculated

### ISSUE THREAD

**Issue by bigtonylewis** [twopirllc/pandas-ta#795]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
No

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
Done

**Is your feature request related to a problem? Please describe.**
In #794 I said that "A `None` is workable" as a return value when, for example, a time series is too short for an indicator to return valid results.  My example was an EMA(101) when you only have 100 price points.

But now I'm frustrated a bit by that, and would prefer something that can be more easily concatenated into other results.  My reason for this is if I am wanting to evaluate a whole bunch of different length EMAs, I currently have to have special code that handles a returned `None`, because I often want to concatenate my results for further processing.  For example:
```python
ema_lengths = [3, 8, 15, 30, 50 100, 200]
my_emas = pd.concat([ta.ema(df.close, ema_length) for ema_length in ema_lengths], axis=1)
```

**Describe the solution you'd like**
I would prefer pandas_ta return the equivalent of:
```python
pd.Series(numpy.nan, index=df.index, name=f'EMA_{length}')`
```
And other variations of names for other indicators.

**Describe alternatives you've considered**
I have this workaround in my code, but think it should be in the library, as I'm sure it would benefit others.

Or maybe there's a keyword `(..., return_none_as_nans=False)` on each indicator if you would prefer to not change the default behaviour.

Thank you!

**Comment by twopirllc** [comment]
Hello @bigtonylewis,

### Example
Adding on to #794 as well. With the _development_ version, one can:

```python
import pandas as pd
import pandas_ta as ta
_df = pd.DataFrame()

df = _df.ta.ticker("spy", period="2y")
df.drop(columns=["Stock Splits", "Dividends"], inplace=True)

# Generate some emas with different window lengths
ws = [_ for _ in range(100, 1100, 400)]
print(ws)
mas = [{"kind": "ema", "length": i} for i in ws]
print(mas)

# Create a Study, set cores=0 and give it a name
cta = ta.Study(name="incremental", ta=mas, cores=0)
print(cta)

# Run the batch and remove verbose=True when not testing
df.ta.study(cta, verbose=True)
print(df)
print(ta.version)
```

Example IPython session:

<img width="816" alt="Screenshot 2024-06-03 at 10 55 54 AM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/d1ca8b22-c4fa-49a9-ae94-dfc9ce81737e">
<img width="628" alt="Screenshot 2024-06-03 at 10 56 09 AM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/9699dfd7-7284-4ddb-b86c-a66d8e0ee04b">

The example above does not append ```EMA_900``` to the _df_ since 900 > 502 (rows) nor a column named ```EMA_900``` filled with _nan_. If this is the undesired workflow and results, contributions are always welcome, especially now. Simply checkout the _development_ branch, edit and submit a PR and we can go from there.  😎

### Preferred Solution
> I would prefer pandas_ta return the equivalent of:
```python
pd.Series(numpy.nan, index=df.index, name=f'EMA_{length}')
```
> And other variations of names for other indicators.

Great! Should be doable.

### Contribution
> I have this workaround in my code, but think it should be in the library, as I'm sure it would benefit others. Or maybe there's a keyword ```(..., return_none_as_nans=False)``` on each indicator if you would prefer to not change the default behaviour.

Default is preferred. 


Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @bigtonylewis,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
