### ISSUE TITLE
Charts - with full data from day one

### ISSUE THREAD

**Issue by ajmal017** [twopirllc/pandas-ta#82]
Currently the charts when displayed, start late, meaning ema15 starts after 15dats, etc.. 

typically we need full charts, where by we need to load previous data and display from the date we needed..

How can we get this thing done

**Comment by twopirllc** [comment]
Hello @ajmal017,

Thanks for checking out ```Pandas TA```!

If you do not like using [TA Lib](https://github.com/mrjbq7/ta-lib)'s implementation of ```ema``` which begins with an ```sma```, you can easily disable it by passing in the keyword argument ```sma=False``` into ```ema``` like so: ```ema15 = ta.ema(close, length=15, sma=False)```.

If you are curious about how to use any ```Pandas TA``` indicator, just do: ```help(ta.indicator)``` for more specific options or calculation adjustments as described on the README.

> How can **we** get this thing done

If any of the indicators are incorrectly calculated, feel free to make adjustments to your fork. Please note, if the indicator also exists in [TA Lib](https://github.com/mrjbq7/ta-lib), make sure that the output is at least 90% correlated, _preferably_ 99% correlated, with ```TA Lib``` before submitting a pull request as well as your corrected rendition as an additional keyword argument for the indicator. If the indicator in question has no corresponding indicator in ```TA Lib```, then all you need to do is submit a pull request.

I look forward to _our_ collaboration and your submissions to help making ```Pandas TA``` a better TA Library for the Python community!

Thanks!
KJ

**Comment by twopirllc** [comment]
Hello @ajmal017,

Curious if you have tried the following regarding ```ema```?
```ema15 = ta.ema(close, length=15, sma=False)```

Thanks,
KJ

**Comment by ajmal017** [comment]
I felt the question was misunderstood, it wasnt about any error or any wrong calculation - its about displaying all variables in a chart in a full way.. https://raw.githubusercontent.com/twopirllc/pandas-ta/master/images/TA_Chart.png take for example this image, the 200 MA is display after 200 days in the chart, so is bands etc  - to display rightly in a chart, we usually take backward data to calculate the SMA but display from the date asked.. 
![image](https://user-images.githubusercontent.com/59230387/89094219-9420ec80-d3d2-11ea-8991-a6b4a63aece1.png)

**Comment by twopirllc** [comment]
> I felt the question was misunderstood, ...

Your original post, did not have a question.

This is a Technical Analysis Library, **not** a charting library. There are plenty of Data Source APIs, Analysis and Backtesting Libraries, Charting Libraries, ML/AI Frameworks and Brokerage APIs required/needed to build an Algo Trading Platform. This is just **one** component, not two or more, of the pipeline that many traders and investors rely upon and use. As such, it is up to the user to display charts to their liking and specifications.

It appears that your real issue is with an **example chart** displaying it's resultant calculations. It is only an example, it shows that SMA and Bollinger Bands are calculating properly because there is no data for values less than it's period of calculation. The SMA200 will not have any data for those first 200 periods, likewise the first 20 periods for Bollinger Bands. Why is that an issue? 🤷‍♂️ Here are some (Matplotlib Charts)[https://github.com/twopirllc/pandas-ta/blob/master/examples/example.ipynb] **without** the period gaps. I have been planning to update the _Example Charts_ in the README anyhow after adding some more indicators.

I spend considerable **free time** to produce an easy to use Open Source Technical Analysis library that is comparable to other de facto Open Source TA Libraries plus other features not commonly found in other libraries. With the rest of my non-existent free time, I am building out the other components of the pipeline for my own Algo Trading Platform. So I would greatly appreciate if future issues are related to adding or improving indicators.

Thank you,
KJ
