### ISSUE TITLE
how to append new data frame?

### ISSUE THREAD

**Issue by qnguye** [twopirllc/pandas-ta#84]
let's say i have 100 rows in data frame, applied all strategies. Now, i want to add 1 more row, i don't want it to recalculate all the whole 101 rows instead only the last one.

**Comment by twopirllc** [comment]
Hello @qnguye,

Thanks for checking out **Pandas TA**!

> let's say i have 100 rows in data frame, applied all strategies. Now, i want to add 1 more row, i don't want it to recalculate all the whole 101 rows instead only the last one.

As it stands, **Pandas TA** does not allow one to just add one more row of calculation easily. Some if not many indicators last value do no rely solely on it's previous value. To keep as much of the code as DRY as possible, many indicators rely on calculations of other indicators.

However I have been told, without any proof of concept or a working solution, that converting **all** the code to *asynchronous* functions would potentially solve that issue. Even with a working solution, it may break other certain features and/or functionality inherent to **Pandas TA** such as the ```strategy()``` method.

In regards to the **ALL Strategy**, while it is convenient and easy to use, it is a sub-optimal solution for developing a reliable TA Strategy. Not just because of the processing time, but also many indicators of the same category share high correlation (or a lot of redundancy). For example in **Momentum** alone, the following indicators such as: ```ao```, ```apo```, ```bias```, ```coppock```, ```kst```, ```macd```, ```mom```, ```ppo```, and ```roc``` all yield "similar" looking charts. That redundancy can be reduced by developing a more targeted strategy as in the [**Pandas TA** Strategy Example Notebook](https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb) Obviously, that would also cut down on computation time. In my opinion, that's what I recommend.

Thoughts? Questions?

Hope this helps!
KJ

**Comment by qnguye** [comment]
I'm new to python, it thought I missed something that's already been there. This library is just awesome the way it is. I guess i have to extract parts of the library for my need. Thank you

**Comment by twopirllc** [comment]
No worries. I wish it were that simple as well.

If you need help constructing a Strategy you have in mind, just let me know.

Please ⭐ if you find the library easy and useful.

Thanks,
KJ
