### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [twopirllc/pandas-ta#841]
In https://github.com/twopirllc/pandas-ta/blob/b465491f226d9e07fffd4e59cd0affc9284521ca/pandas_ta/utils/_core.py#L45 there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if any exception is raised from the `try` body (including `BaseException` such as `KeyboardInterrupt`), it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by twopirllc** [comment]
Hello @iritkatriel 

Thanks for point the mistake out. Since _v3.14_, the _development_ branch has had many improvements including "better" [validators](https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/utils/_validate.py). Checkout the _development_ branch and let me know what you think. If you have any improvements to mak, please make a PR. Any help is greatly apprecaited. 😎 

Kind Regards,
KJ
