### ISSUE TITLE
Elder Force Index

### ISSUE THREAD

**Issue by SoftDevDanial** [twopirllc/pandas-ta#90]
Hi , 

For the EFI , according to your formula here, you get the difference of current close price - prior close price * volume then you do the exponential weighted average for it. I may have the wrong understanding of it but according to investopedia and thinkorswim, the formula is current close price - prior close price * VFI(13)[ a.k.a 13 period ema of the force index]

Investopedia
![image](https://user-images.githubusercontent.com/64815604/89695145-8d035c80-d945-11ea-88e5-8e1dc48e01b8.png)

Thinkorswim
![image](https://user-images.githubusercontent.com/64815604/89695186-a5737700-d945-11ea-8d3d-c0c07b3ef25b.png)

**Comment by twopirllc** [comment]
Hi @SoftDevDanial,

I first test against the de fact **TA Lib** if there is a corresponding indicator with that library. Since **efi** is not supported by **TA Lib**, I used TradingView's formulas for calculations. There are many brokerages sometimes with their own calculations of indicators. Can you provide convincing evidence that the current **efi** is being incorrectly calculated? Do you have correlation tests?

I am open to alternative calculations if there is significant difference from well known libraries or if you just want a seperate brokerage/platform version, then please contribute by forking the library, add a kwarg option like ```tos``` and the additional calculation, make sure all the tests pass and then make a pull request.

I look forward to your future contributions to making ```Pandas TA``` an easy to use and robust TA library.

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
Hi,
I checked and your formula is correct.. When i tested your efi, i used thinkorswim to check if the value are similar with your formula and it was close but not the same which led to me believing that the force index of thinkorswim could be different from your efi. I had a sudden thought that the data i retrieve from yahoo finance via yahoo query api could have a slight difference number for both price and volume. Apparently, i was right as the volume were not the same where thinkorswim volume was more accurate compared to yahoo finance. After some manual changes the outcome was similar. So i guess this can be closed.

Thanks,
Danial

**Comment by twopirllc** [comment]
Hello @SoftDevDanial,

Yeah, multiple sources are not 100% correlated. Thanks for double checking.

Regards,
KJ
